### ISSUE TITLE
Unstoppable gradient overflow in stage 2 image caption

### ISSUE THREAD

**Issue by dannyxiaocn** [OFA-Sys/OFA#108]
Hi, after my moe-ofa model got the cider score of 1.294 in the stage 1, I feed the `checkpoint_best.pt` into stage 2 training in image caption. And it gives back this:
```
2022-05-16 22:33:57 - trainer.py[line:722] - INFO: begin training epoch 1
2022-05-16 22:33:57 - train.py[line:303] - INFO: Start iterating over samples
/workspace/OFA/criterions/scst_moe_loss.py:218: RuntimeWarning: invalid value encountered in true_divide
  baseline = (sc_.sum(1, keepdims=True) - sc_) / (sc_.shape[1] - 1)
2022-05-16 22:34:05 - trainer.py[line:945] - INFO: NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 64.0
2022-05-16 22:34:07 - trainer.py[line:945] - INFO: NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 32.0
2022-05-16 22:34:09 - trainer.py[line:945] - INFO: NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 16.0
2022-05-16 22:34:12 - trainer.py[line:945] - INFO: NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 8.0
2022-05-16 22:34:14 - trainer.py[line:945] - INFO: NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 4.0
2022-05-16 22:34:17 - trainer.py[line:945] - INFO: NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 2.0
2022-05-16 22:34:19 - trainer.py[line:945] - INFO: NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 1.0
2022-05-16 22:34:22 - trainer.py[line:945] - INFO: NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 0.5
2022-05-16 22:34:24 - trainer.py[line:945] - INFO: NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 0.25
2022-05-16 22:34:26 - trainer.py[line:945] - INFO: NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 0.125
2022-05-16 22:34:29 - trainer.py[line:945] - INFO: NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 0.0625
2022-05-16 22:34:31 - trainer.py[line:945] - INFO: NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 0.03125
2022-05-16 22:34:34 - trainer.py[line:945] - INFO: NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 0.015625
2022-05-16 22:34:36 - trainer.py[line:945] - INFO: NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 0.0078125
2022-05-16 22:34:38 - trainer.py[line:945] - INFO: NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 0.00390625
2022-05-16 22:34:41 - trainer.py[line:945] - INFO: NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 0.001953125
2022-05-16 22:34:43 - trainer.py[line:945] - INFO: NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 0.0009765625
2022-05-16 22:34:45 - trainer.py[line:945] - INFO: NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 0.00048828125
2022-05-16 22:34:47 - trainer.py[line:945] - INFO: NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 0.000244140625
2022-05-16 22:34:49 - trainer.py[line:945] - INFO: NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 0.0001220703125
/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py:787: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "
/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py:752: UserWarning: Using non-full backward hooks on a Module that does not return a single Tensor or a tuple of Tensors is deprecated and will be removed in future versions. This hook will be missing some of the grad_output. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using non-full backward hooks on a Module that does not return a "
/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py:777: UserWarning: Using a non-full backward hook when outputs are generated by different autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_output. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when outputs are generated by different autograd Nodes "
Traceback (most recent call last):
  File "/workspace/OFA/trainer.py", line 890, in train_step
    grad_norm = self.clip_grad_norm(self.cfg.optimization.clip_norm)
  File "/workspace/OFA/trainer.py", line 1237, in clip_grad_norm
    return self.optimizer.clip_grad_norm(
  File "/workspace/OFA/fairseq/fairseq/optim/fp16_optimizer.py", line 426, in clip_grad_norm
    self.scaler.check_overflow(grad_norm_cpu)
  File "/workspace/OFA/fairseq/fairseq/optim/dynamic_loss_scaler.py", line 61, in check_overflow
    raise FloatingPointError(
FloatingPointError: Minimum loss scale reached (0.0001). Your loss is probably exploding. Try lowering the learning rate, using gradient clipping or increasing the batch size.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../train.py", line 558, in <module>
    cli_main()
  File "../../train.py", line 551, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/workspace/OFA/fairseq/fairseq/distributed/utils.py", line 387, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/workspace/OFA/fairseq/fairseq/distributed/utils.py", line 361, in distributed_main
    main(cfg, **kwargs)
  File "../../train.py", line 197, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "../../train.py", line 308, in train
    log_output = trainer.train_step(samples)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/OFA/trainer.py", line 933, in train_step
    self.task.train_step(
  File "/workspace/OFA/tasks/ofa_task.py", line 320, in train_step
    loss, sample_size, logging_output = criterion(model, sample, update_num=update_num)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 881, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/OFA/criterions/scst_moe_loss.py", line 130, in forward
    loss, moe_loss, score, ntokens, nsentences = self.compute_loss(model, sample, reduce=reduce)
  File "/workspace/OFA/criterions/scst_moe_loss.py", line 286, in compute_loss
    net_output, gen_target_tokens = self.get_net_output(model, sample, gen_target)
  File "/workspace/OFA/criterions/scst_moe_loss.py", line 261, in get_net_output
    net_output = model(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 881, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/OFA/models/ofa/ofa.py", line 89, in forward
    encoder_out = self.encoder(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 897, in _call_impl
    var = next((v for v in var.values() if isinstance(v, torch.Tensor)))
StopIteration
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
```
I have turn the clip_norm=0.0, and adjust the batch_size(bigger or smaller) wouldn't help. So do you have any clue about this?
Also, I have found a really strange thing that if I recover the training from the previous saved checkpoint in the same training stage, the loss will not match with the loss in the previous broken process ( like loss=2.8 in the previous one, but after recover it starts from loss=4.0 ). Is this phenomenon normal? Or this shows there are some problems with the checkpoint saving and loading.

**Comment by JustinLin610** [comment]
What is your setup for learning rate?

**Comment by dannyxiaocn** [comment]
This is my config. lr is 1e-7.
```
#!/usr/bin/env

# The port for communication. Note that if you want to run multiple tasks on the same machine,
# you need to specify different port numbers.
export MASTER_PORT=2052

log_dir=./moe_stage2_logs
save_dir=./moe_stage2_checkpoints
mkdir -p $log_dir $save_dir

bpe_dir=../../utils/BPE
user_dir=../../ofa_module

data_dir=../../dataset/caption_data
data=${data_dir}/caption_stage2_train.tsv,${data_dir}/caption_val.tsv
restore_file=./moe_only_encoder_stage1_checkpoints/10_0.06_2500/checkpoint_best.pt
selected_cols=1,4,2

task=caption
arch=ofa_moe_base
criterion=scst_reward_moe_criterion
label_smoothing=0.1
lr=1e-7
max_epoch=5
warmup_ratio=0.06
batch_size=2
update_freq=4
resnet_drop_path_rate=0.0
encoder_drop_path_rate=0.0
decoder_drop_path_rate=0.0
dropout=0.0
attention_dropout=0.0
max_src_length=80
max_tgt_length=20
num_bins=1000
patch_image_size=480
eval_cider_cached=${data_dir}/cider_cached_tokens/coco-valid-words.p
scst_cider_cached=${data_dir}/cider_cached_tokens/coco-train-words.p
drop_worst_ratio=0.2
moe_gate_loss_wt=0.01
moe_combine_method="sum"
moe_second_expert_policy="all"
moe_normalize_expert_grad="sqrt_world_size"

for lr in {1e-5,}; do
  echo "lr "${lr}
  for max_epoch in {5,}; do
    echo "max_epoch "${max_epoch}

    log_file=${log_dir}/${lr}"_"${max_epoch}".log"
    save_path=${save_dir}/${lr}"_"${max_epoch}
    mkdir -p $save_path

    CUDA_VISIBLE_DEVICES=1 python3 -m torch.distributed.launch --nproc_per_node=1 --master_port=${MASTER_PORT} ../../train.py \
        $data \
        --selected-cols=${selected_cols} \
        --bpe-dir=${bpe_dir} \
        --user-dir=${user_dir} \
        --restore-file=${restore_file} \
        --reset-optimizer --reset-dataloader --reset-meters \
        --save-dir=${save_path} \
        --task=${task} \
        --arch=${arch} \
        --criterion=${criterion} \
        --batch-size=${batch_size} \
        --update-freq=${update_freq} \
        --encoder-normalize-before \
        --decoder-normalize-before \
        --share-decoder-input-output-embed \
        --share-all-embeddings \
        --layernorm-embedding \
        --patch-layernorm-embedding \
        --code-layernorm-embedding \
        --resnet-drop-path-rate=${resnet_drop_path_rate} \
        --encoder-drop-path-rate=${encoder_drop_path_rate} \
        --decoder-drop-path-rate=${decoder_drop_path_rate} \
        --dropout=${dropout} \
        --attention-dropout=${attention_dropout} \
        --weight-decay=0.01 --optimizer=adam --adam-betas="(0.9,0.999)" --adam-eps=1e-08 --clip-norm=0.0 \
        --lr-scheduler=polynomial_decay --lr=${lr} --end-learning-rate=2e-7 \
        --max-epoch=${max_epoch} --warmup-ratio=${warmup_ratio} \
        --log-format=simple --log-interval=10 \
        --fixed-validation-seed=7 \
        --no-epoch-checkpoints --keep-best-checkpoints=1 \
        --save-interval=1 --validate-interval=1 \
        --save-interval-updates=500 --validate-interval-updates=500 \
        --eval-cider \
        --eval-cider-cached-tokens=${eval_cider_cached} \
        --eval-args='{"beam":1,"max_len_b":16,"no_repeat_ngram_size":3}' \
        --best-checkpoint-metric=cider --maximize-best-checkpoint-metric \
        --max-src-length=${max_src_length} \
        --max-tgt-length=${max_tgt_length} \
        --find-unused-parameters \
        --freeze-encoder-embedding \
        --freeze-decoder-embedding \
		    --freeze-resnet \
        --add-type-embedding \
        --scale-attn \
        --scale-fc \
        --scale-heads \
        --moe-expert-count=4 \
        --moe-gating-use-fp32 \
        --moe-freq=0 \
        --encoder-moe-freq=2 \
        --decoder-moe-freq=0 \
        --moe-second-expert-policy=${moe_second_expert_policy} \
        --moe-normalize-gate-prob-before-dropping \
        --moe-top1-expert \
        --moe-normalize-expert-grad=${sqrt_world_size} \
        --use-moe-pad-mask \
        --disable-entangle \
        --num-bins=${num_bins} \
        --patch-image-size=${patch_image_size} \
        --scst \
        --scst-cider-cached-tokens=${scst_cider_cached} \
        --scst-args='{"beam":1,"max_len_b":16,"no_repeat_ngram_size":3}' \
        --memory-efficient-fp16 \
        --fp16-scale-window=512 \
        --num-workers=0 > ${log_file} 2>&1
  done
done
```

**Comment by JustinLin610** [comment]
Better use a smaller one in stage 2. I often use 1e-6 or 8e-7 cuz it is really unstable.
