### ISSUE TITLE
CUDA error: CUBLAS_STATUS_ALLOC_FAILED when I run vq-gan generator script

### ISSUE THREAD

**Issue by taokz** [OFA-Sys/OFA#121]
Hi! Thanks for your amazing work and your active replies to issues!

I have an issue when I run 'generate_for_vqgan_code.sh' using my customized dataset. I follow the guidance to create an (image-only) input files (.txt) like:

12345 \t /9j/4AAQSkZJ....UCP/2Q== \n
12346 \t /9j/4AAQSkZJ....UCP/2W== \n
...
where \t means tabs, \n means newlines. I use images with 390x320 size.

However, when I run the script, I got RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling cublasCreate(handle). The details are shown as follows:

Traceback (most recent call last):
File "generate_code.py", line 121, in
z, , [, _, image_codes] = image_tokenizer.encode(data["code_image"].cuda())
File "../../models/taming/models/vqgan.py", line 55, in encode
h = self.encoder(x)
File "/home/test/anaconda3/envs/test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
return forward_call(*input, **kwargs)
File "../../models/taming/modules/diffusionmodules/model.py", line 418, in forward
h = self.down[i_level].attn[i_block](https://github.com/OFA-Sys/OFA/issues/h)
File "/home/test/anaconda3/envs/test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in call_impl
return forward_call(*input, **kwargs)
File "../../models/taming/modules/diffusionmodules/model.py", line 180, in forward
w = torch.bmm(q,k) # b,hw,hw w[b,i,j]=sum_c q[b,i,c]k[b,c,j]
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling cublasCreate(handle)

Could you provide some hints and suggestions to help solve this issue. I appreciate your help, thanks!

**Comment by jxst539246** [comment]
hi, maybe you can add CUDA_LAUNCH_BLOCKING=1  to get more details?
`CUDA_LAUNCH_BLOCKING=1 python generate_code.py ... `
