### ISSUE TITLE
Custom vis-lan dataset - RuntimeError: stack expects each tensor to be equal size, but got [3, 256, 256] at entry 0 and [3, 320, 390] at entry 2

### ISSUE THREAD

**Issue by taokz** [OFA-Sys/OFA#125]
Thank you for your amazing work. 

When I use your code to pretrain the model, I got a runtime error as follows:

Traceback (most recent call last):
  File "../../train.py", line 528, in <module>
    cli_main()
  File "../../train.py", line 521, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/test/ofa/fairseq/fairseq/distributed/utils.py", line 374, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/home/test/ofa/fairseq/fairseq/distributed/utils.py", line 348, in distributed_main
    main(cfg, **kwargs)
  File "../../train.py", line 161, in main
    disable_iterator_cache=True,
  File "/home/test/ofa/utils/checkpoint_utils.py", line 288, in load_checkpoint
    epoch=1, load_dataset=True, **passthrough_args
  File "/home/test/ofa/trainer.py", line 666, in get_train_iterator
    self.reset_dummy_batch(batch_iterator.first_batch)
  File "/home/test/ofa/fairseq/fairseq/data/iterators.py", line 322, in first_batch
    return self.collate_fn([self.dataset[i] for i in self.frozen_batches[0]])
  File "/home/test/ofa/data/pretrain_data/unify_dataset.py", line 636, in collater
    res_v2 = collate(samples_v2, pad_idx=self.src_dict.pad(), eos_idx=self.eos)
  File "/home/test/ofa/data/pretrain_data/unify_dataset.py", line 70, in collate
    patch_images = torch.stack([sample['patch_image'] for sample in samples], dim=0)
RuntimeError: stack expects each tensor to be equal size, but got [3, 256, 256] at entry 0 and [3, 320, 390] at entry 2

The mismatch size would also be [3, 320, 320] sometimes. I tried to use different datasets, but I got the same error, and this error only happens when I use my customized visualization_language.tsv. I followed readme to create the .tsv file as follows:

unique_id | image (base64 string) | caption | question | answer | ground_truth objects | dataset name | task type
--              | --                                    | --          | --            | --          | --                                  | --                    | --

The base64 string is generated by your provided code as show in other issues. 

Since the size of images vary, should I resize images before generating base64 string? However, according to issue [106](https://github.com/OFA-Sys/OFA/issues/106), you state that 

The resizing from the raw size to the specified resolution is done on the fly during training and inference in the __getitem__ method of pytorch dataset.

I think you mean that I do not need to resize image, and your code will help me do it. Could you clarify this issue? I appreciate your help, thank you!

**Comment by yangapku** [comment]
Hi, could you please provide more details about your experimental setting? I guess you are trying to perform OFA pretraining. For pretraining, according to the readme, the data files `vision_language_examples.tsv` (for multi-modal pretraining tasks), `text_examples.tsv` (for text-only pretraining tasks), `image_examples.tsv` (for image-only pretraining tasks) and `detection_examples.tsv` (for detection pretraining tasks) should be prepared to facilitate our multitask pretraining. These files have different schema as mentioned in the readme. (The schema you provide is for `vision_language_examples.tsv`.) Have you prepared all these files or just some of them? The error is most likely to be related to `image_examples.tsv` rather than `vision_language_examples.tsv` which should contain images with their VQ-GAN codes. For this pretraining task, the images should be pre-resized into 256*256 and fed into the VQ-GAN to obtain the image code. For other pretraining tasks and for fine-tuning, as mentioned in #106 (which is related to image captioning finetuning), the resize will be done on-the-fly.

**Comment by taokz** [comment]
Hi, 

Yes, I am trying to perform pretraining. I created 4 corresponding files with my own data according to readme. (I does not pre-resize images before feeding into VQ-GAN).  However, I didn't see error when loading other files rather than vision_language tsv. That's why I think error is most likely to be related to vision_language_examples.tsv. The details are shown in following (I ignore some unnecessary contents).

2022-06-15 13:01:03 - ofa_task.py[line:102] - INFO: source dictionary: 59457 types
2022-06-15 13:01:03 - ofa_task.py[line:103] - INFO: target dictionary: 59457 types
local datafile /data/omnimed/processed_data/text/text_example.tsv slice_id 0 begin to initialize row_count and line_idx-to-offset mapping
local datafile /data/omnimed/processed_data/text/text_example.tsv slice_id 0 finished initializing row_count and line_idx-to-offset mapping
file /data/omnimed/processed_data/text/text_example.tsv slice_id 0 row count 2000 total row count 2000
local datafile /data/omnimed/processed_data/image/chexpert.tsv slice_id 0 begin to initialize row_count and line_idx-to-offset mapping
local datafile /data/omnimed/processed_data/image/chexpert.tsv slice_id 0 finished initializing row_count and line_idx-to-offset mapping
file /data/omnimed/processed_data/image/chexpert.tsv slice_id 0 row count 223414 total row count 223414
local datafile /data/omnimed/processed_data/detection/deep_lesion.tsv slice_id 0 begin to initialize row_count and line_idx-to-offset mapping
local datafile /data/omnimed/processed_data/detection/deep_lesion.tsv slice_id 0 finished initializing row_count and line_idx-to-offset mapping
file /data/omnimed/processed_data/detection/deep_lesion.tsv slice_id 0 row count 9624 total row count 9624
/home/kaz321/anaconda3/envs/omnimed/lib/python3.7/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755953518/work/aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
2022-06-15 13:01:17 - train.py[line:101] - INFO: OFAModel(
.........

2022-06-15 13:01:17 - train.py[line:102] - INFO: task: UnifyTask
2022-06-15 13:01:17 - train.py[line:103] - INFO: model: OFAModel
2022-06-15 13:01:17 - train.py[line:104] - INFO: criterion: AdjustLabelSmoothedCrossEntropyCriterion
2022-06-15 13:01:17 - train.py[line:108] - INFO: num. shared model params: 182,238,536 (num. trained: 182,238,536)
2022-06-15 13:01:17 - train.py[line:115] - INFO: num. expert model params: 0 (num. trained: 0)
local datafile /data/omnimed/processed_data/vis_lan/peir_gross.tsv slice_id 0 begin to initialize row_count and line_idx-to-offset mapping
local datafile /data/omnimed/processed_data/vis_lan/peir_gross.tsv slice_id 0 finished initializing row_count and line_idx-to-offset mapping
file /data/omnimed/processed_data/vis_lan/peir_gross.tsv slice_id 0 row count 7443 total row count 7443
2022-06-15 13:01:18 - trainer.py[line:124] - INFO: detected shared parameter: encoder.embed_tokens.weight <- decoder.embed_tokens.weight
2022-06-15 13:01:18 - trainer.py[line:124] - INFO: detected shared parameter: encoder.embed_tokens.weight <- decoder.output_projection.weight
2022-06-15 13:01:18 - trainer.py[line:124] - INFO: detected shared parameter: encoder.embed_images.conv1.bias <- encoder.embed_images.layer1.0.conv1.bias
2022-06-15 13:01:18 - trainer.py[line:124] - INFO: detected shared parameter: encoder.embed_images.conv1.bias <- encoder.embed_images.layer1.0.conv2.bias
2022-06-15 13:01:18 - trainer.py[line:124] - INFO: detected shared parameter: encoder.embed_images.conv1.bias <- encoder.embed_images.layer1.0.conv3.bias
2022-06-15 13:01:18 - trainer.py[line:124] - INFO: detected shared parameter: encoder.embed_images.conv1.bias <- encoder.embed_images.layer1.0.downsample.0.bias
.........

2022-06-15 13:01:18 - utils.py[line:759] - INFO: ***********************CUDA enviroments for all 1 workers***********************
2022-06-15 13:01:18 - utils.py[line:765] - INFO: rank   0: capabilities =  8.6  ; total memory = 23.688 GB ; name = NVIDIA RTX A5000
2022-06-15 13:01:18 - utils.py[line:767] - INFO: ***********************CUDA enviroments for all 1 workers***********************
2022-06-15 13:01:18 - train.py[line:145] - INFO: training on 1 devices (GPUs/TPUs)
2022-06-15 13:01:18 - train.py[line:151] - INFO: max tokens per device = None and max sentences per device = 4
2022-06-15 13:01:18 - trainer.py[line:458] - INFO: Preparing to load checkpoint ../../checkpoints/ofa_base.pt
2022-06-15 13:01:20 - trainer.py[line:619] - INFO: Loaded checkpoint ../../checkpoints/ofa_base.pt (epoch 48 @ 0 updates)
2022-06-15 13:01:20 - trainer.py[line:639] - INFO: loading train data for epoch 1
local datafile /data/omnimed/processed_data/vis_lan/peir_gross.tsv slice_id 0 begin to initialize row_count and line_idx-to-offset mapping
local datafile /data/omnimed/processed_data/vis_lan/peir_gross.tsv slice_id 0 finished initializing row_count and line_idx-to-offset mapping
file /data/omnimed/processed_data/vis_lan/peir_gross.tsv slice_id 0 row count 7443 total row count 7443
/home/kaz321/anaconda3/envs/omnimed/lib/python3.7/site-packages/torchvision/transforms/functional.py:424: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
Traceback (most recent call last):
  File "../../train.py", line 528, in <module>
    cli_main()
  File "../../train.py", line 521, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/kaz321/omnimed/fairseq/fairseq/distributed/utils.py", line 374, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/home/kaz321/omnimed/fairseq/fairseq/distributed/utils.py", line 348, in distributed_main
    main(cfg, **kwargs)
  File "../../train.py", line 161, in main
    disable_iterator_cache=True,
  File "/home/kaz321/omnimed/utils/checkpoint_utils.py", line 288, in load_checkpoint
    epoch=1, load_dataset=True, **passthrough_args
  File "/home/kaz321/omnimed/trainer.py", line 666, in get_train_iterator
    self.reset_dummy_batch(batch_iterator.first_batch)
  File "/home/kaz321/omnimed/fairseq/fairseq/data/iterators.py", line 322, in first_batch
    return self.collate_fn([self.dataset[i] for i in self.frozen_batches[0]])
  File "/home/kaz321/omnimed/data/pretrain_data/unify_dataset.py", line 636, in collater
    res_v2 = collate(samples_v2, pad_idx=self.src_dict.pad(), eos_idx=self.eos)
  File "/home/kaz321/omnimed/data/pretrain_data/unify_dataset.py", line 70, in collate
    patch_images = torch.stack([sample['patch_image'] for sample in samples], dim=0)
RuntimeError: stack expects each tensor to be equal size, but got [3, 256, 256] at entry 0 and [3, 320, 320] at entry 2
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3059480) of binary: /home/kaz321/anaconda3/envs/omnimed/bin/python3
Traceback (most recent call last):
  File "/home/kaz321/anaconda3/envs/omnimed/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kaz321/anaconda3/envs/omnimed/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kaz321/anaconda3/envs/omnimed/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/kaz321/anaconda3/envs/omnimed/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/kaz321/anaconda3/envs/omnimed/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/kaz321/anaconda3/envs/omnimed/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/home/kaz321/anaconda3/envs/omnimed/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/kaz321/anaconda3/envs/omnimed/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by taokz** [comment]
Thank you SO MUCH for your reply, I've resize images before feeding into VQ-GAN for ```image_examples.tsv``` and it solves my previous problem. However, I encounter the other error -- it seems that the input sequence is longer than the maximum input sequence length (1024). 

Traceback (most recent call last):
  File "../../train.py", line 528, in <module>
    cli_main()
  File "../../train.py", line 521, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/kaz321/omnimed/fairseq/fairseq/distributed/utils.py", line 374, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/home/kaz321/omnimed/fairseq/fairseq/distributed/utils.py", line 348, in distributed_main
    main(cfg, **kwargs)
  File "../../train.py", line 190, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/home/kaz321/anaconda3/envs/omnimed/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "../../train.py", line 301, in train
    log_output = trainer.train_step(samples)
  File "/home/kaz321/anaconda3/envs/omnimed/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/kaz321/omnimed/trainer.py", line 806, in train_step
    raise e
  File "/home/kaz321/omnimed/trainer.py", line 780, in train_step
    **extra_kwargs,
  File "/home/kaz321/omnimed/tasks/ofa_task.py", line 318, in train_step
    loss, sample_size, logging_output = criterion(model, sample, update_num=update_num)
  File "/home/kaz321/anaconda3/envs/omnimed/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kaz321/omnimed/criterions/label_smoothed_cross_entropy.py", line 180, in forward
    loss_v2, sample_size_v2, logging_output_v2 = self.forward(model, sample[1], update_num, reduce)
  File "/home/kaz321/omnimed/criterions/label_smoothed_cross_entropy.py", line 199, in forward
    net_output = model(**sample["net_input"])
  File "/home/kaz321/anaconda3/envs/omnimed/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kaz321/omnimed/models/ofa/ofa.py", line 107, in forward
    return_all_hiddens=return_all_hiddens,
  File "/home/kaz321/anaconda3/envs/omnimed/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kaz321/omnimed/models/ofa/unify_transformer.py", line 1169, in forward
    alignment_heads=alignment_heads,
  File "/home/kaz321/omnimed/models/ofa/unify_transformer.py", line 1193, in extract_features
    alignment_heads,
  File "/home/kaz321/omnimed/models/ofa/unify_transformer.py", line 1316, in extract_features_scriptable
    self_attn_bias[~code_masks] += self.get_rel_pos_bias(all_prev_output_tokens, idx).unsqueeze(0)
```RuntimeError: The size of tensor a (1025) must match the size of tensor b (1024) at non-singleton dimension 3```

**Comment by logicwong** [comment]
Thanks for pointing this out! After the image is resized to 256*256, you also need to crop the middle 128*128 part and feed it to VQ-GAN. Image Infilling is actually restoring the middle part of the image. We will update Readme later.

![Uploading CFCDA8C9-963B-4A43-A90E-A544030D4161.png…]()

**Comment by taokz** [comment]
Hi, I've followed your instructions, 1) resize original images to be 256 * 256 and generated their base64 string -- ```image_string.tsv```; 2) crop middle part and generate its base64 string ```mid_image_string.tsv```; 3) use the base64 string of middle part and VQ-GAN to generate the image code ```mid_image_code.tsv```; 4) combine base64 string of 256*256 image and code of 128*128 as input ```image_examples.tsv```.

But I still have the ```RuntimeError: The size of tensor a (1025) must match the size of tensor b (1024) at non-singleton dimension 3``` as described previously. I think the input format of my customized data is correct. My preprocess codes are as follows:

```python
ext = ('.jpg')
parser = argparse.ArgumentParser()
parser.add_argument('--mode', type=int, default=0, help='0: resize to (256*256), or 1: capture middle part (128*128) string, or 2: base64 string, or 3: combine image-code via vq-gan')
args = parser.parse_args()

if args.mode == 0:
    count = 0
    path_of_the_directory = '../a_dataset/image/train'
    save_path_of_the_directory = '../a_dataset/image/train_resize'
    for path, dirc, files in os.walk(path_of_the_directory):
        for name in files:
            if name.endswith(ext):
                count += 1

                file_directory = os.path.join(path, name)
                try:
                    # using OpenCV
                    img = cv2.imread(file_directory)
                    # resize to be (256, 256)
                    img = cv2.resize(img, (256, 256), interpolation=cv2.INTER_CUBIC)
                    # save images
                    name = name[:-4] + '_' + str(count) + '.jpg'
                    save_name = os.path.join(save_path_of_the_directory, name)
                    cv2.imwrite(save_name , img)

                except Exception as e:
                    pass 
                if count % 1000 == 0:
                    print("processed", count, "images!")
                continue
    print("compeleted! # of total instances:", count)

if args.mode == 1:
    # used to be fed into VQ-GAN
    path_of_the_directory = '../a_dataset/image/train_resize'
    count = 0
    with open("../a_dataset/mid_image_string.tsv", 'w') as out_file:
        for path, dirc, files in os.walk(path_of_the_directory):
            for name in files:
                if name.endswith(ext):
                    count += 1
                    file_directory = os.path.join(path, name)
                    # crop middle part (128*128)
                    frac = 0.50
                    left = img.size[0]*((1-frac)/2)
                    upper = img.size[1]*((1-frac)/2)
                    right = img.size[0]-((1-frac)/2)*img.size[0]
                    bottom = img.size[1]-((1-frac)/2)*img.size[1]
                    cropped_img = img.crop((left, upper, right, bottom))
                    
                    img_buffer = BytesIO()
                    cropped_img.save(img_buffer, format=img.format)
                    byte_data = img_buffer.getvalue()
                    base64_str = base64.b64encode(byte_data)
                    base64_str = base64_str.decode("utf-8")
                    out_file.write('1_' + str(count) + '\t' + base64_str + '\n')
                    if count % 1000 == 0:
                        print("processed", count, "images!")
    print("compeleted! # of total instances:", count)

if args.mode == 2:
    path_of_the_directory = '../a_dataset/CheXpert-v1.0-small/train_resize'
    count = 0
    with open("../a_dataset/image_string.tsv", 'w') as out_file:
        for path, dirc, files in os.walk(path_of_the_directory):
            for name in files:
                if name.endswith(ext):
                    count += 1
                    file_directory = os.path.join(path, name)
                    try:
                        img = Image.open(file_directory)
                        img_buffer = BytesIO()
                        img.save(img_buffer, format=img.format)
                        byte_data = img_buffer.getvalue()
                        base64_str = base64.b64encode(byte_data)
                        base64_str = base64_str.decode("utf-8")
                        out_file.write('1_' + str(count) + '\t' + base64_str + '\n')
                    except Exception as e:
                        pass 
                    if count % 1000 == 0:
                        print("processed", count, "images!")
                    continue
    print("compeleted! # of total instances:", count)

if args.mode == 3:
    count = 0
    with open("../a_dataset/image_string.tsv", 'r') as f1, open("../a_dataset/mid_image_code.tsv", 'r') as f2:
        with open("../a_dataset/image_examples.tsv", 'w') as out:
            for x,y in zip(csv.reader(f1, delimiter='\t'),csv.reader(f2, delimiter='\t')):
                out.write(x[0] + '\t' + x[1] + '\t' + y[1] + '\n')
                count += 1
                if count % 1000 == 0:
                    print("processed", count, "images!")
    print("compeleted! # of total instances:", count)
```

Thanks!

**Comment by taokz** [comment]
According to the VQ-GAN code, the code_image_size is 256, but I got 1024. I am figuring out what's going on. 

<img width="502" alt="image" src="https://user-images.githubusercontent.com/31445846/174719427-f5f7427f-517c-4acc-8403-0de8a4a07c6b.png">

**Comment by logicwong** [comment]
@taokz Hi, I think you should set `--code_image_size=128`

**Comment by taokz** [comment]
Thanks, it works!
