### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by Jihyun0510** [OFA-Sys/OFA#130]
Hello

I tried finetuning large model for image captioning but I keep getting subprocess.CalledProcessError.
I've tried various numbers for Port number but it did not work out.
What could be the possible reason for this error? (though it seems like a gpu distribution issue...)
Thank you so much for your help

```
export MASTER_PORT=1052

log_dir=./stage2_logs
save_dir=./stage2_checkpoints
mkdir -p $log_dir $save_dir

bpe_dir=../../utils/BPE
user_dir=../../ofa_module

data_dir=../../dataset/caption_data
data=${data_dir}/caption_train_stage2_new.tsv,${data_dir}/caption_val_ct.tsv
restore_file=../../checkpoints/caption_stage1_best.pt
selected_cols=1,4,2

task=caption
arch=ofa_large
criterion=scst_reward_criterion
label_smoothing=0.1
lr=1e-5
max_epoch=5
warmup_ratio=0.06
batch_size=1
update_freq=4
resnet_drop_path_rate=0.0
encoder_drop_path_rate=0.0
decoder_drop_path_rate=0.0
dropout=0.0
attention_dropout=0.0
max_src_length=80
max_tgt_length=20
num_bins=1000
patch_image_size=480
eval_cider_cached=${data_dir}/cider_cached_tokens/coco-valid-words.p
scst_cider_cached=${data_dir}/cider_cached_tokens/coco-train-words.p

for lr in 5e-6,; do
  echo "lr "${lr}
  for max_epoch in 5; do
    echo "max_epoch "${max_epoch}

    log_file=${log_dir}/${lr}"_"${max_epoch}".log"
    save_path=${save_dir}/${lr}"_"${max_epoch}
    mkdir -p $save_path

    CUDA_VISIBLE_DEVICES=1,2 python3 -m torch.distributed.launch --nproc_per_node=2 --master_port=${MASTER_PORT} ../../train.py \
        $data \
        --selected-cols=${selected_cols} \
        --bpe-dir=${bpe_dir} \
        --user-dir=${user_dir} \
        --restore-file=${restore_file} \
        --reset-optimizer --reset-dataloader --reset-meters \
        --save-dir=${save_path} \
        --task=${task} \
        --arch=${arch} \
        --criterion=${criterion} \
        --batch-size=${batch_size} \
        --update-freq=${update_freq} \
        --encoder-normalize-before \
        --decoder-normalize-before \
        --share-decoder-input-output-embed \
        --share-all-embeddings \
        --layernorm-embedding \
        --patch-layernorm-embedding \
        --code-layernorm-embedding \
        --resnet-drop-path-rate=${resnet_drop_path_rate} \
        --encoder-drop-path-rate=${encoder_drop_path_rate} \
        --decoder-drop-path-rate=${decoder_drop_path_rate} \
        --dropout=${dropout} \
        --attention-dropout=${attention_dropout} \
        --weight-decay=0.01 --optimizer=adam --adam-betas="(0.9,0.999)" --adam-eps=1e-08 --clip-norm=1.0 \
        --lr-scheduler=polynomial_decay --lr=${lr} --end-learning-rate=2e-7 \
        --max-epoch=${max_epoch} --warmup-ratio=${warmup_ratio} \
        --log-format=simple --log-interval=10 \
        --fixed-validation-seed=7 \
        --no-epoch-checkpoints --keep-best-checkpoints=1 \
        --save-interval=1 --validate-interval=1 \
        --save-interval-updates=500 --validate-interval-updates=500 \
        --eval-cider \
        --eval-cider-cached-tokens=${eval_cider_cached} \
        --eval-args='{"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}' \
        --best-checkpoint-metric=cider --maximize-best-checkpoint-metric \
        --max-src-length=${max_src_length} \
        --max-tgt-length=${max_tgt_length} \
        --find-unused-parameters \
        --freeze-encoder-embedding \
        --freeze-decoder-embedding \
        --freeze-resnet \
        --add-type-embedding \
        --scale-attn \
        --scale-fc \
        --scale-heads \
        --disable-entangle \
        --num-bins=${num_bins} \
        --patch-image-size=${patch_image_size} \
        --scst \
        --scst-cider-cached-tokens=${scst_cider_cached} \
        --scst-args='{"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}' \
        --memory-efficient-fp16 \
        --fp16-scale-window=512 \
        --num-workers=0 > ${log_file} 2>&1
  done
done
```

**Comment by logicwong** [comment]
@Jihyun0510 Try fine-tuning with a single GPU first to see if it can train normally?

**Comment by Jihyun0510** [comment]
> @Jihyun0510 Try fine-tuning with a single GPU first to see if it can train normally? `CUDA_VISIBLE_DEVICES=1 python3 ../../train.py`

It is still giving the same error... so this is not a gpu distribution issue?

**Comment by logicwong** [comment]
It's not a distribution issue. Can you provide the full training log?

**Comment by Jihyun0510** [comment]
> It's not a distribution issue. Can you provide the full training log?

Sure!

```

2022-06-19 18:20:06 - utils.py[line:258] - INFO: distributed init (rank 0): env://
2022-06-19 18:20:06 - utils.py[line:261] - INFO: Start init
Retry: 1, with value error <class 'RuntimeError'>
Traceback (most recent call last):
  File "/home/jsh/miniconda3/envs/jh/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jsh/miniconda3/envs/jh/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jsh/miniconda3/envs/jh/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/jsh/miniconda3/envs/jh/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/jsh/miniconda3/envs/jh/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/jsh/miniconda3/envs/jh/bin/python3', '-u', '../../train.py', '--local_rank=0', '../../dataset/caption_data/caption_train_stage2_new.tsv,../../dataset/caption_data/caption_val_ct.tsv', '--selected-cols=1,4,2', '--bpe-dir=../../utils/BPE', '--user-dir=../../ofa_module', '--restore-file=../../checkpoints/caption_stage1_best.pt', '--reset-optimizer', '--reset-dataloader', '--reset-meters', '--save-dir=./stage2_checkpoints/5e-6,_5', '--task=caption', '--arch=ofa_large', '--criterion=scst_reward_criterion', '--batch-size=1', '--update-freq=4', '--encoder-normalize-before', '--decoder-normalize-before', '--share-decoder-input-output-embed', '--share-all-embeddings', '--layernorm-embedding', '--patch-layernorm-embedding', '--code-layernorm-embedding', '--resnet-drop-path-rate=0.0', '--encoder-drop-path-rate=0.0', '--decoder-drop-path-rate=0.0', '--dropout=0.0', '--attention-dropout=0.0', '--weight-decay=0.01', '--optimizer=adam', '--adam-betas=(0.9,0.999)', '--adam-eps=1e-08', '--clip-norm=1.0', '--lr-scheduler=polynomial_decay', '--lr=5e-6,', '--end-learning-rate=2e-7', '--max-epoch=5', '--warmup-ratio=0.06', '--log-format=simple', '--log-interval=10', '--fixed-validation-seed=7', '--no-epoch-checkpoints', '--keep-best-checkpoints=1', '--save-interval=1', '--validate-interval=1', '--save-interval-updates=500', '--validate-interval-updates=500', '--eval-cider', '--eval-cider-cached-tokens=../../dataset/caption_data/cider_cached_tokens/coco-valid-words.p', '--eval-args={"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}', '--best-checkpoint-metric=cider', '--maximize-best-checkpoint-metric', '--max-src-length=80', '--max-tgt-length=20', '--find-unused-parameters', '--freeze-encoder-embedding', '--freeze-decoder-embedding', '--freeze-resnet', '--add-type-embedding', '--scale-attn', '--scale-fc', '--scale-heads', '--disable-entangle', '--num-bins=1000', '--patch-image-size=480', '--scst', '--scst-cider-cached-tokens=../../dataset/caption_data/cider_cached_tokens/coco-train-words.p', '--scst-args={"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}', '--memory-efficient-fp16', '--fp16-scale-window=512', '--num-workers=0']' returned non-zero exit status 255.
Killing subprocess 2384127
```

**Comment by logicwong** [comment]
@Jihyun0510  Provide me with a single-GPU training log? That will help me find the bugs more easily.

**Comment by Jihyun0510** [comment]
@logicwong 

Yes of course

training scripts:
```
export MASTER_PORT=1052

log_dir=./stage2_logs
save_dir=./stage2_checkpoints
mkdir -p $log_dir $save_dir

bpe_dir=../../utils/BPE
user_dir=../../ofa_module

data_dir=../../dataset/caption_data
data=${data_dir}/caption_train_stage2_new.tsv,${data_dir}/caption_val_ct.tsv
restore_file=../../checkpoints/caption_stage1_best.pt
selected_cols=1,4,2

task=caption
arch=ofa_large
criterion=scst_reward_criterion
label_smoothing=0.1
lr=1e-5
max_epoch=5
warmup_ratio=0.06
batch_size=1
update_freq=4
resnet_drop_path_rate=0.0
encoder_drop_path_rate=0.0
decoder_drop_path_rate=0.0
dropout=0.0
attention_dropout=0.0
max_src_length=80
max_tgt_length=20
num_bins=1000
patch_image_size=480
eval_cider_cached=${data_dir}/cider_cached_tokens/coco-valid-words.p
scst_cider_cached=${data_dir}/cider_cached_tokens/coco-train-words.p

for lr in 5e-6,; do
  echo "lr "${lr}
  for max_epoch in 5; do
    echo "max_epoch "${max_epoch}

    log_file=${log_dir}/${lr}"_"${max_epoch}".log"
    save_path=${save_dir}/${lr}"_"${max_epoch}
    mkdir -p $save_path

    CUDA_VISIBLE_DEVICES=1 python3 -m torch.distributed.launch --nproc_per_node=1 --master_port=${MASTER_PORT} ../../train.py \
        $data \
        --selected-cols=${selected_cols} \
        --bpe-dir=${bpe_dir} \
        --user-dir=${user_dir} \
        --restore-file=${restore_file} \
        --reset-optimizer --reset-dataloader --reset-meters \
        --save-dir=${save_path} \
        --task=${task} \
        --arch=${arch} \
        --criterion=${criterion} \
        --batch-size=${batch_size} \
        --update-freq=${update_freq} \
        --encoder-normalize-before \
        --decoder-normalize-before \
        --share-decoder-input-output-embed \
        --share-all-embeddings \
        --layernorm-embedding \
        --patch-layernorm-embedding \
        --code-layernorm-embedding \
        --resnet-drop-path-rate=${resnet_drop_path_rate} \
        --encoder-drop-path-rate=${encoder_drop_path_rate} \
        --decoder-drop-path-rate=${decoder_drop_path_rate} \
        --dropout=${dropout} \
        --attention-dropout=${attention_dropout} \
        --weight-decay=0.01 --optimizer=adam --adam-betas="(0.9,0.999)" --adam-eps=1e-08 --clip-norm=1.0 \
        --lr-scheduler=polynomial_decay --lr=${lr} --end-learning-rate=2e-7 \
        --max-epoch=${max_epoch} --warmup-ratio=${warmup_ratio} \
        --log-format=simple --log-interval=10 \
        --fixed-validation-seed=7 \
        --no-epoch-checkpoints --keep-best-checkpoints=1 \
        --save-interval=1 --validate-interval=1 \
        --save-interval-updates=500 --validate-interval-updates=500 \
        --eval-cider \
        --eval-cider-cached-tokens=${eval_cider_cached} \
        --eval-args='{"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}' \
        --best-checkpoint-metric=cider --maximize-best-checkpoint-metric \
        --max-src-length=${max_src_length} \
        --max-tgt-length=${max_tgt_length} \
        --find-unused-parameters \
        --freeze-encoder-embedding \
        --freeze-decoder-embedding \
        --freeze-resnet \
        --add-type-embedding \
        --scale-attn \
        --scale-fc \
        --scale-heads \
        --disable-entangle \
        --num-bins=${num_bins} \
        --patch-image-size=${patch_image_size} \
        --scst \
        --scst-cider-cached-tokens=${scst_cider_cached} \
        --scst-args='{"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}' \
        --memory-efficient-fp16 \
        --fp16-scale-window=512 \
        --num-workers=0 > ${log_file} 2>&1
  done
done
````

logs:
````
2022-06-19 22:15:57 - utils.py[line:258] - INFO: distributed init (rank 0): env://
2022-06-19 22:15:57 - utils.py[line:261] - INFO: Start init
Retry: 1, with value error <class 'RuntimeError'>
Traceback (most recent call last):
  File "/home/jsh/miniconda3/envs/jh/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jsh/miniconda3/envs/jh/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jsh/miniconda3/envs/jh/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/jsh/miniconda3/envs/jh/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/jsh/miniconda3/envs/jh/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/jsh/miniconda3/envs/jh/bin/python3', '-u', '../../train.py', '--local_rank=0', '../../dataset/caption_data/caption_train_stage2_new.tsv,../../dataset/caption_data/caption_val_ct.tsv', '--selected-cols=1,4,2', '--bpe-dir=../../utils/BPE', '--user-dir=../../ofa_module', '--restore-file=../../checkpoints/caption_stage1_best.pt', '--reset-optimizer', '--reset-dataloader', '--reset-meters', '--save-dir=./stage2_checkpoints/5e-6,_5', '--task=caption', '--arch=ofa_large', '--criterion=scst_reward_criterion', '--batch-size=1', '--update-freq=4', '--encoder-normalize-before', '--decoder-normalize-before', '--share-decoder-input-output-embed', '--share-all-embeddings', '--layernorm-embedding', '--patch-layernorm-embedding', '--code-layernorm-embedding', '--resnet-drop-path-rate=0.0', '--encoder-drop-path-rate=0.0', '--decoder-drop-path-rate=0.0', '--dropout=0.0', '--attention-dropout=0.0', '--weight-decay=0.01', '--optimizer=adam', '--adam-betas=(0.9,0.999)', '--adam-eps=1e-08', '--clip-norm=1.0', '--lr-scheduler=polynomial_decay', '--lr=5e-6,', '--end-learning-rate=2e-7', '--max-epoch=5', '--warmup-ratio=0.06', '--log-format=simple', '--log-interval=10', '--fixed-validation-seed=7', '--no-epoch-checkpoints', '--keep-best-checkpoints=1', '--save-interval=1', '--validate-interval=1', '--save-interval-updates=500', '--validate-interval-updates=500', '--eval-cider', '--eval-cider-cached-tokens=../../dataset/caption_data/cider_cached_tokens/coco-valid-words.p', '--eval-args={"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}', '--best-checkpoint-metric=cider', '--maximize-best-checkpoint-metric', '--max-src-length=80', '--max-tgt-length=20', '--find-unused-parameters', '--freeze-encoder-embedding', '--freeze-decoder-embedding', '--freeze-resnet', '--add-type-embedding', '--scale-attn', '--scale-fc', '--scale-heads', '--disable-entangle', '--num-bins=1000', '--patch-image-size=480', '--scst', '--scst-cider-cached-tokens=../../dataset/caption_data/cider_cached_tokens/coco-train-words.p', '--scst-args={"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}', '--memory-efficient-fp16', '--fp16-scale-window=512', '--num-workers=0']' returned non-zero exit status 255.
Killing subprocess 2492606
````

**Comment by logicwong** [comment]
@Jihyun0510 Please change `CUDA_VISIBLE_DEVICES=1 python3 -m torch.distributed.launch --nproc_per_node=1 --master_port=${MASTER_PORT} ../../train.py` to `CUDA_VISIBLE_DEVICES=1 python3 ../../train.py` and try again...

**Comment by Jihyun0510** [comment]
> 

sorry I did not catch the message write away.
I changed the line and changed pytorch versions which solved the problem above. 
However it is rasing AssertionError: 16 < 16.
This is strange because I am using exactly the same dataset and weights that worked on another server.

```
2022-06-19 23:09:08 - utils.py[line:759] - INFO: ***********************CUDA enviroments for all 2 workers***********************
2022-06-19 23:09:08 - utils.py[line:765] - INFO: rank   0: capabilities =  8.6  ; total memory = 23.697 GB ; name = NVIDIA GeForce RTX 3090                 
2022-06-19 23:09:08 - utils.py[line:765] - INFO: rank   1: capabilities =  8.6  ; total memory = 23.700 GB ; name = NVIDIA GeForce RTX 3090                 
2022-06-19 23:09:08 - utils.py[line:767] - INFO: ***********************CUDA enviroments for all 2 workers***********************
2022-06-19 23:09:08 - train.py[line:150] - INFO: training on 2 devices (GPUs/TPUs)
2022-06-19 23:09:08 - train.py[line:156] - INFO: max tokens per device = None and max sentences per device = 1
2022-06-19 23:09:08 - trainer.py[line:458] - INFO: Preparing to load checkpoint ../../checkpoints/caption_stage1_best.pt
2022-06-19 23:09:08 - trainer.py[line:624] - INFO: No existing checkpoint found ../../checkpoints/caption_stage1_best.pt
2022-06-19 23:09:08 - trainer.py[line:639] - INFO: loading train data for epoch 1
local datafile ../../dataset/caption_data/caption_train_stage2_new.tsv slice_id 0 begin to initialize row_count and line_idx-to-offset mapping
local datafile ../../dataset/caption_data/caption_train_stage2_new.tsv slice_id 0 finished initializing row_count and line_idx-to-offset mapping
file ../../dataset/caption_data/caption_train_stage2_new.tsv slice_id 0 row count 56644 total row count 113287
slice_id 0 seek offset 0
Total steps 70805, warmup steps 4248, warmup_factor 0.00023540489642184556
2022-06-19 23:09:10 - trainer.py[line:703] - INFO: begin training epoch 1
2022-06-19 23:09:10 - train.py[line:301] - INFO: Start iterating over samples
single-machine distributed training is initialized.
local datafile ../../dataset/caption_data/caption_val_ct.tsv slice_id 1 begin to initialize row_count and line_idx-to-offset mapping
local datafile ../../dataset/caption_data/caption_val_ct.tsv slice_id 1 finished initializing row_count and line_idx-to-offset mapping
file ../../dataset/caption_data/caption_val_ct.tsv slice_id 1 row count 2500 total row count 5000
local datafile ../../dataset/caption_data/caption_train_stage2_new.tsv slice_id 1 begin to initialize row_count and line_idx-to-offset mapping
local datafile ../../dataset/caption_data/caption_train_stage2_new.tsv slice_id 1 finished initializing row_count and line_idx-to-offset mapping
file ../../dataset/caption_data/caption_train_stage2_new.tsv slice_id 1 row count 56643 total row count 113287
slice_id 1 seek offset 56644
Total steps 70805, warmup steps 4248, warmup_factor 0.00023540489642184556
/home/jsh/miniconda3/envs/ofa/lib/python3.7/site-packages/torchvision/transforms/transforms.py:258: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
/home/jsh/miniconda3/envs/ofa/lib/python3.7/site-packages/torchvision/transforms/transforms.py:258: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
Traceback (most recent call last):
  File "../../train.py", line 533, in <module>
    cli_main()
  File "../../train.py", line 526, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/jsh/miniconda3/envs/ofa/lib/python3.7/site-packages/fairseq/distributed/utils.py", line 371, in call_main
    join=True,
  File "/home/jsh/miniconda3/envs/ofa/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/jsh/miniconda3/envs/ofa/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/jsh/miniconda3/envs/ofa/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/jsh/miniconda3/envs/ofa/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/jsh/miniconda3/envs/ofa/lib/python3.7/site-packages/fairseq/distributed/utils.py", line 348, in distributed_main
    main(cfg, **kwargs)
  File "/home/jsh/OFA/train.py", line 195, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/home/jsh/miniconda3/envs/ofa/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/jsh/OFA/train.py", line 306, in train
    log_output = trainer.train_step(samples)
  File "/home/jsh/miniconda3/envs/ofa/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/jsh/OFA/trainer.py", line 780, in train_step
    **extra_kwargs,
  File "/home/jsh/OFA/tasks/ofa_task.py", line 318, in train_step
    loss, sample_size, logging_output = criterion(model, sample, update_num=update_num)
  File "/home/jsh/miniconda3/envs/ofa/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jsh/OFA/criterions/scst_loss.py", line 88, in forward
    loss, score, ntokens, nsentences = self.compute_loss(model, sample, reduce=reduce)
  File "/home/jsh/OFA/criterions/scst_loss.py", line 239, in compute_loss
    gen_target, gen_res, gt_res = self.get_generator_out(model, sample)
  File "/home/jsh/OFA/criterions/scst_loss.py", line 149, in get_generator_out
    gen_out = self.task.scst_generator.generate([model], sample)
  File "/home/jsh/miniconda3/envs/ofa/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/jsh/OFA/models/sequence_generator.py", line 207, in generate
    return self._generate(models, sample, **kwargs)
  File "/home/jsh/OFA/models/sequence_generator.py", line 480, in _generate
    assert step < max_len, f"{step} < {max_len}"
AssertionError: 16 < 16
```

**Comment by logicwong** [comment]
For stable CIDEr optimization, the model used in stage2 should be initialized with the model trained at stage1. It seems that the stage1 model is not placed in the correct directory.

![CD527AF4-A187-4C2F-8C26-60C1CEDECAEE](https://user-images.githubusercontent.com/36780733/174488182-8f4fb265-ae2e-466d-91c0-d0348a44929a.png)

**Comment by Jihyun0510** [comment]
> For stable CIDEr optimization, the model used in stage2 should be initialized with the model trained at stage1. It seems that the stage1 model is not placed in the correct directory.
> 
> ![CD527AF4-A187-4C2F-8C26-60C1CEDECAEE](https://user-images.githubusercontent.com/36780733/174488182-8f4fb265-ae2e-466d-91c0-d0348a44929a.png)

oh that was such a foolish mistake of me!
Now it is working!
Thank you so much for your help
