### ISSUE TITLE
KeyError: 'net_input' when pertaining OFA with multi-GPUs

### ISSUE THREAD

**Issue by taokz** [OFA-Sys/OFA#140]
Hi, 

I would like to perform pertaining with multiple GPUs, and I have a ```KeyError: 'net_input'```. I just modified GPU allocation part of the original ```pretrain_ofa_base.sh```:
```python
export CUDA_VISIBLE_DEVICES=4,5,6,7,8,9
export GPUS_PER_NODE=6
```

The error happens during training instead of the beginning as shown in the following. 
```console
2022-06-22 19:52:53 - progress_bar.py[line:274] - INFO: epoch 001:   1329 / 2899 loss=11.106, loss_v1=1.471, loss_v2=9.719, nll_loss=11.101, ntokens=2239.9, nsentences=36, sample_size=6, sample_size_v1=194, sample_size_v2=2045.9, ppl=2196.75, wps=6273.6, ups=2.8, wpb=2239.9, bsz=36, num_updates=1320, lr=5.49983e-05, gnorm=5.7, clip=90, loss_scale=32, train_wall=4, gb_free=17.6, wall=507
2022-06-22 19:52:56 - progress_bar.py[line:274] - INFO: epoch 001:   1339 / 2899 loss=11.427, loss_v1=1.589, loss_v2=9.89, nll_loss=11.409, ntokens=2195.7, nsentences=36, sample_size=6, sample_size_v1=184.8, sample_size_v2=2010.9, ppl=2719.77, wps=6071, ups=2.76, wpb=2195.7, bsz=36, num_updates=1330, lr=5.46499e-05, gnorm=5.402, clip=50, loss_scale=32, train_wall=4, gb_free=17.6, wall=510
2022-06-22 19:53:00 - progress_bar.py[line:274] - INFO: epoch 001:   1349 / 2899 loss=11.255, loss_v1=1.643, loss_v2=9.754, nll_loss=11.241, ntokens=2221.7, nsentences=36, sample_size=6, sample_size_v1=189, sample_size_v2=2032.7, ppl=2420.75, wps=6180.7, ups=2.78, wpb=2221.7, bsz=36, num_updates=1340, lr=5.43016e-05, gnorm=5.359, clip=60, loss_scale=32, train_wall=4, gb_free=17.6, wall=514
2022-06-22 19:53:03 - progress_bar.py[line:274] - INFO: epoch 001:   1359 / 2899 loss=11.376, loss_v1=1.445, loss_v2=10.039, nll_loss=11.368, ntokens=2175.5, nsentences=36, sample_size=6, sample_size_v1=196.5, sample_size_v2=1979, ppl=2643.64, wps=6101.9, ups=2.8, wpb=2175.5, bsz=36, num_updates=1350, lr=5.39533e-05, gnorm=5.594, clip=60, loss_scale=32, train_wall=4, gb_free=17.6, wall=518
Traceback (most recent call last):
  File "../../train.py", line 528, in <module>
    cli_main()
  File "../../train.py", line 521, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/user/OFA/fairseq/fairseq/distributed/utils.py", line 374, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/home/user/OFA/fairseq/fairseq/distributed/utils.py", line 348, in distributed_main
    main(cfg, **kwargs)
  File "../../train.py", line 190, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/home/user/anaconda3/envs/omnimed/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "../../train.py", line 301, in train
    log_output = trainer.train_step(samples)
  File "/home/user/anaconda3/envs/omnimed/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/user/OFA/trainer.py", line 780, in train_step
    **extra_kwargs,
  File "/home/user/OFA/tasks/ofa_task.py", line 318, in train_step
    loss, sample_size, logging_output = criterion(model, sample, update_num=update_num)
  File "/home/user/anaconda3/envs/omnimed/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/OFA/criterions/label_smoothed_cross_entropy.py", line 178, in forward
    sample[0]['net_input']['sample_patch_num'] = self.sample_patch_num
KeyError: 'net_input'
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3076654 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3076655 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3076656 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3076657 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3076658 closing signal SIGTERM
```

I've also tried single GPU training and I did not get the same error. 
```console
2022-06-22 21:48:16 - progress_bar.py[line:274] - INFO: epoch 001:  17374 / 17393 loss=9.522, loss_v1=0.766, loss_v2=8.761, nll_loss=9.444, ntokens=376.4, nsentences=6, sample_size=1, sample_size_v1=5.3, sample_size_v2=371.1, ppl=696.39, wps=1167.6, ups=3.1, wpb=376.4, bsz=6, num_updates=17270, lr=7.14286e-07, gnorm=17.834, clip=100, loss_scale=512, train_wall=3, gb_free=17.8, wall=6071
2022-06-22 21:48:19 - progress_bar.py[line:274] - INFO: epoch 001:  17384 / 17393 loss=9.631, loss_v1=0.223, loss_v2=9.379, nll_loss=9.595, ntokens=343.8, nsentences=6, sample_size=1, sample_size_v1=4.6, sample_size_v2=339.2, ppl=773.17, wps=1088.5, ups=3.17, wpb=343.8, bsz=6, num_updates=17280, lr=6.56214e-07, gnorm=14.148, clip=100, loss_scale=512, train_wall=3, gb_free=18, wall=6074
2022-06-22 21:48:22 - checkpoint_utils.py[line:64] - INFO: Preparing to save checkpoint for epoch 1 @ 17289 updates
2022-06-22 21:48:22 - trainer.py[line:431] - INFO: Saving checkpoint to ./checkpoints/checkpoint1.pt
2022-06-22 21:48:27 - trainer.py[line:441] - INFO: Finished saving checkpoint to ./checkpoints/checkpoint1.pt
2022-06-22 21:48:29 - checkpoint_utils.py[line:135] - INFO: Saved checkpoint ./checkpoints/checkpoint1.pt (epoch 1 @ 17289 updates, score None) (writing took 7.106163591146469 seconds)
2022-06-22 21:48:29 - train.py[line:323] - INFO: end of epoch 1 (average epoch stats below)
```

Could you give me some hints when I run multi-GPU training? Thanks a lot!

**Comment by logicwong** [comment]
@taokz Thanks for your pointing out the issue. Our code may have a bug when constructing batches under distributed training. As shown in the figure below (tasks/ofa_task.py), in some cases, the last GPU may not be allocated data, which may be the reason for the error. Can you change batch_sampler.append([]) to batch_sampler.append([1]) and test it again?

![20C00FD9-FC67-484C-98AC-281B68C5D86F](https://user-images.githubusercontent.com/36780733/175198818-1908e7c6-3a4d-44fa-bfdc-a899fbf19494.png)

**Comment by taokz** [comment]
Thank you for your quick reply. It solves my issue! 

Besides, I have a quick question: Is it possible to use one source dataset (e.g. only image.tsv without others) to pretrain the OFA model with the existing code? 

Thanks again!

**Comment by logicwong** [comment]
> Thank you for your quick reply. It solves my issue!
> 
> Besides, I have a quick question: Is it possible to use one source dataset (e.g. only image.tsv without others) to pretrain the OFA model with the existing code?
> 
> Thanks again!

Of course, you only need to modify `tasks/pretrain_tasks/unify_task.py` and `data/pretrain_data/unify_dataset.py`. For `data/pretrain_data/unify_dataset.py`, I think modify __getitem__() and collater() are enough.
