### ISSUE TITLE
"Key 'use_ema_weights_to_init_param' is not in struct"/"please ensure that the architectures match" when trying to fine-tune ofa-base

### ISSUE THREAD

**Issue by SilverSolver** [OFA-Sys/OFA#146]
Hello and thank you for releasing the code of OFA model(s).
I'm currently trying to fine-tune OFA-base on the custom image caption dataset. For this purpose, I'm using slightly modified version of `train_caption_stage1.sh` script, where I set `arch=ofa_base` and `restore_file=../../checkpoints/ofa_base.pt` (downloaded from your `checkpoints.md` page yesterday). As the result, I get the following error:

```
 /home/laida/miniconda3/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
/home/laida/miniconda3/lib/python3.8/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/laida/miniconda3/lib/python3.8/site-packages/torchvision/transforms/transforms.py:332: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
Traceback (most recent call last):
  File "/home/laida/new_SSD/NLP_in_RL_experiments/OFA/trainer.py", line 504, in load_checkpoint
    if self.cfg.checkpoint.use_ema_weights_to_init_param and "extra_state" in state and "ema" in state["extra_state"]:
  File "/home/laida/miniconda3/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 305, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/laida/miniconda3/lib/python3.8/site-packages/omegaconf/base.py", line 95, in _format_and_raise
    format_and_raise(
  File "/home/laida/miniconda3/lib/python3.8/site-packages/omegaconf/_utils.py", line 629, in format_and_raise
    _raise(ex, cause)
  File "/home/laida/miniconda3/lib/python3.8/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
  File "/home/laida/miniconda3/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 303, in __getattr__
    return self._get_impl(key=key, default_value=DEFAULT_VALUE_MARKER)
  File "/home/laida/miniconda3/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 361, in _get_impl
    node = self._get_node(key=key)
  File "/home/laida/miniconda3/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 383, in _get_node
    self._validate_get(key)
  File "/home/laida/miniconda3/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 135, in _validate_get
    self._format_and_raise(
  File "/home/laida/miniconda3/lib/python3.8/site-packages/omegaconf/base.py", line 95, in _format_and_raise
    format_and_raise(
  File "/home/laida/miniconda3/lib/python3.8/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/home/laida/miniconda3/lib/python3.8/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigAttributeError: Key 'use_ema_weights_to_init_param' is not in struct
        full_key: checkpoint.use_ema_weights_to_init_param
        reference_type=Any
        object_type=dict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../train.py", line 528, in <module>
    cli_main()
  File "../../train.py", line 521, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/laida/miniconda3/lib/python3.8/site-packages/fairseq/distributed/utils.py", line 354, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/home/laida/miniconda3/lib/python3.8/site-packages/fairseq/distributed/utils.py", line 328, in distributed_main
    main(cfg, **kwargs)
  File "../../train.py", line 157, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(
  File "/home/laida/new_SSD/NLP_in_RL_experiments/OFA/utils/checkpoint_utils.py", line 249, in load_checkpoint
    extra_state = trainer.load_checkpoint(
  File "/home/laida/new_SSD/NLP_in_RL_experiments/OFA/trainer.py", line 524, in load_checkpoint
    raise Exception(
Exception: Cannot load model parameters from checkpoint ../../checkpoints/ofa_base.pt; please ensure that the architectures match.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 31950) of binary: /home/laida/miniconda3/bin/python3
Traceback (most recent call last):
  File "/home/laida/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/laida/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/laida/miniconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/laida/miniconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/laida/miniconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/laida/miniconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/laida/miniconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/laida/miniconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
../../train.py FAILED
```

I ensured that I use the latest OFA code and `ofa_base.pt`, as well as re-installed fairseq, as it was suggested in this issue: https://github.com/OFA-Sys/OFA/issues/126 . But nothing helped.

Here is some info about my setup:
- My HEAD is on OFA's commit ` 630e193986824ab90bce659a747994a3d0667bf4` from Jun 23, 2022
- My fairseq version is 0.12.2
- My omegaconf version is 2.0.6 (I tried to update omegaconf to 2.2.2, but got error `ImportError: cannot import name 'get_ref_type' from 'omegaconf._utils'` , so I had to roll back to 2.0.6)
- My torchvision version is 0.12.0+cu102
- My torch version is 1.11.0+cu102
- My pip version is 21.2.4

**Comment by logicwong** [comment]
@SilverSolver Hi, I think you should install Fairseq library provided **in our repo** instead of the official Fairseq repo.

`pip install -e ./fairseq/`

**Comment by SilverSolver** [comment]
@logicwong Thank you for a quick answer! I installed Fairseq from your repo as suggested. Now it's version is `1.0.0a0+630e193`. However, now I see another error, connected with architecture mismatch:

```
/home/laida/miniconda3/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
/home/laida/miniconda3/lib/python3.8/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/laida/miniconda3/lib/python3.8/site-packages/torchvision/transforms/transforms.py:332: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
Traceback (most recent call last):
  File "/home/laida/new_SSD/NLP_in_RL_experiments/OFA/trainer.py", line 511, in load_checkpoint
    self.model.load_state_dict(
  File "/home/laida/new_SSD/NLP_in_RL_experiments/OFA/fairseq/fairseq/models/fairseq_model.py", line 125, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/home/laida/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for OFAModel:
        Unexpected key(s) in state_dict: "encoder.layers.0.attn_ln.weight", "encoder.layers.0.attn_ln.bias", "encoder.layers.0.ffn_layernorm.weight", "encoder.layers.0.ffn_layernorm.bias", "encoder.layers.0.self_attn.c_attn", "encoder.layers.1.attn_ln.weight", "encoder.layers.1.attn_ln.bias", "encoder.layers.1.ffn_layernorm.weight", "encoder.layers.1.ffn_layernorm.bias", "encoder.layers.1.self_attn.c_attn", "encoder.layers.2.attn_ln.weight", "encoder.layers.2.attn_ln.bias", "encoder.layers.2.ffn_layernorm.weight", "encoder.layers.2.ffn_layernorm.bias", "encoder.layers.2.self_attn.c_attn", "encoder.layers.3.attn_ln.weight", "encoder.layers.3.attn_ln.bias", "encoder.layers.3.ffn_layernorm.weight", "encoder.layers.3.ffn_layernorm.bias", "encoder.layers.3.self_attn.c_attn", "encoder.layers.4.attn_ln.weight", "encoder.layers.4.attn_ln.bias", "encoder.layers.4.ffn_layernorm.weight", "encoder.layers.4.ffn_layernorm.bias", "encoder.layers.4.self_attn.c_attn", "encoder.layers.5.attn_ln.weight", "encoder.layers.5.attn_ln.bias", "encoder.layers.5.ffn_layernorm.weight", "encoder.layers.5.ffn_layernorm.bias", "encoder.layers.5.self_attn.c_attn", "decoder.layers.0.self_attn_ln.weight", "decoder.layers.0.self_attn_ln.bias", "decoder.layers.0.cross_attn_ln.weight", "decoder.layers.0.cross_attn_ln.bias", "decoder.layers.0.ffn_layernorm.weight", "decoder.layers.0.ffn_layernorm.bias", "decoder.layers.0.self_attn.c_attn", "decoder.layers.0.encoder_attn.c_attn", "decoder.layers.1.self_attn_ln.weight", "decoder.layers.1.self_attn_ln.bias", "decoder.layers.1.cross_attn_ln.weight", "decoder.layers.1.cross_attn_ln.bias", "decoder.layers.1.ffn_layernorm.weight", "decoder.layers.1.ffn_layernorm.bias", "decoder.layers.1.self_attn.c_attn", "decoder.layers.1.encoder_attn.c_attn", "decoder.layers.2.self_attn_ln.weight", "decoder.layers.2.self_attn_ln.bias", "decoder.layers.2.cross_attn_ln.weight", "decoder.layers.2.cross_attn_ln.bias", "decoder.layers.2.ffn_layernorm.weight", "decoder.layers.2.ffn_layernorm.bias", "decoder.layers.2.self_attn.c_attn", "decoder.layers.2.encoder_attn.c_attn", "decoder.layers.3.self_attn_ln.weight", "decoder.layers.3.self_attn_ln.bias", "decoder.layers.3.cross_attn_ln.weight", "decoder.layers.3.cross_attn_ln.bias", "decoder.layers.3.ffn_layernorm.weight", "decoder.layers.3.ffn_layernorm.bias", "decoder.layers.3.self_attn.c_attn", "decoder.layers.3.encoder_attn.c_attn", "decoder.layers.4.self_attn_ln.weight", "decoder.layers.4.self_attn_ln.bias", "decoder.layers.4.cross_attn_ln.weight", "decoder.layers.4.cross_attn_ln.bias", "decoder.layers.4.ffn_layernorm.weight", "decoder.layers.4.ffn_layernorm.bias", "decoder.layers.4.self_attn.c_attn", "decoder.layers.4.encoder_attn.c_attn", "decoder.layers.5.self_attn_ln.weight", "decoder.layers.5.self_attn_ln.bias", "decoder.layers.5.cross_attn_ln.weight", "decoder.layers.5.cross_attn_ln.bias", "decoder.layers.5.ffn_layernorm.weight", "decoder.layers.5.ffn_layernorm.bias", "decoder.layers.5.self_attn.c_attn", "decoder.layers.5.encoder_attn.c_attn".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../train.py", line 528, in <module>
    cli_main()
  File "../../train.py", line 521, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/laida/new_SSD/NLP_in_RL_experiments/OFA/fairseq/fairseq/distributed/utils.py", line 374, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/home/laida/new_SSD/NLP_in_RL_experiments/OFA/fairseq/fairseq/distributed/utils.py", line 348, in distributed_main
    main(cfg, **kwargs)
  File "../../train.py", line 157, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(
  File "/home/laida/new_SSD/NLP_in_RL_experiments/OFA/utils/checkpoint_utils.py", line 249, in load_checkpoint
    extra_state = trainer.load_checkpoint(
  File "/home/laida/new_SSD/NLP_in_RL_experiments/OFA/trainer.py", line 524, in load_checkpoint
    raise Exception(
Exception: Cannot load model parameters from checkpoint ../../checkpoints/ofa_base.pt; please ensure that the architectures match.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 13396) of binary: /home/laida/miniconda3/bin/python3
Traceback (most recent call last):
  File "/home/laida/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/laida/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/laida/miniconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/laida/miniconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/laida/miniconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/laida/miniconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/laida/miniconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/laida/miniconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
../../train.py FAILED
```

**Comment by logicwong** [comment]
@SilverSolver Looks like you removed `--scale-attn`, `--scale-fc`, `--scale-heads`? If so, adding them back will solve your problem.

**Comment by SilverSolver** [comment]
@logicwong Okay, it seems that now stage 1 training is going as it should. Thank you for quick answers, once again!
