### ISSUE TITLE
system error: 10049 - The requested address is not valid in its context.

### ISSUE THREAD

**Issue by yimingsu01** [OFA-Sys/OFA#152]
Hi, 

Thank you for releasing the code and implementation.

I'm trying to replicate the result. I've cloned the repo and downloaded the [Dataset for Caption](https://ofa-beijing.oss-cn-beijing.aliyuncs.com/datasets/caption_data/caption_data.zip) and a model checkpoint for `OFA_base`. I have organized my workspace in the structure suggested.

I tried running `bash pretrain_ofa_base.sh` to resume training, but I received the following errors:
```
NOTE: Redirects are currently not supported in Windows or MacOs.
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:1020 (system error: 10049 - The requested address is not valid in its context.).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:1020 (system error: 10049 - The requested address is not valid in its context.).
2022-07-03 17:11:00 - utils.py[line:255] - INFO: distributed init (rank 0): env://
2022-07-03 17:11:00 - utils.py[line:261] - INFO: Start init
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:1020 (system error: 10049 - The requested address is not valid in its context.).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:1020 (system error: 10049 - The requested address is not valid in its context.).
Retry: 1, with value error <class 'RuntimeError'>
D:\conda_things\conda_envs\ofa\lib\site-packages\torch\distributed\launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 4294967295) local_rank: 0 (pid: 8992) of binary: D:\conda_things\conda_envs\ofa\python.exe
Traceback (most recent call last):
  File "D:\conda_things\conda_envs\ofa\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\conda_things\conda_envs\ofa\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\conda_things\conda_envs\ofa\lib\site-packages\torch\distributed\launch.py", line 193, in <module>
    main()
  File "D:\conda_things\conda_envs\ofa\lib\site-packages\torch\distributed\launch.py", line 189, in main
    launch(args)
  File "D:\conda_things\conda_envs\ofa\lib\site-packages\torch\distributed\launch.py", line 174, in launch
    run(args)
  File "D:\conda_things\conda_envs\ofa\lib\site-packages\torch\distributed\run.py", line 752, in run
    elastic_launch(
  File "D:\conda_things\conda_envs\ofa\lib\site-packages\torch\distributed\launcher\api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "D:\conda_things\conda_envs\ofa\lib\site-packages\torch\distributed\launcher\api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
../../train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-07-03_17:11:00
  host      : XXX.XXX.XXX.XXX
  rank      : 0 (local_rank: 0)
  exitcode  : 4294967295 (pid: 8992)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

Any idea how to fix this issue? Thanks!

**Comment by logicwong** [comment]
@yimingsu01 Are you trying to reproduce the result of Image captioning? If so, you should run `run_scripts/caption/train_caption_stage1_base.sh`

**Comment by yimingsu01** [comment]
Oops I closed it by mistake, the issue hasn't been solve yet. Sorry

**Comment by yimingsu01** [comment]
I solved the issue by replicated the production environment described in the repo
```
python 3.7.4
pytorch 1.8.1
torchvision 0.9.1
```
