### ISSUE TITLE
Unsuccessful GLUE fine-tuning 

### ISSUE THREAD

**Issue by dannyxiaocn** [OFA-Sys/OFA#26]
Hi, when I follow the procedure of glue fine-tuning ( let's say mnli for example), there is a RuntimeError triggered, which goes like:
```2022-03-04 13:14:31 - trainer.py[line:703] - INFO: begin training epoch 1
2022-03-04 13:14:31 - train.py[line:295] - INFO: Start iterating over samples
slice_id 1 seek offset 98176
Total steps 30680, warmup steps 1840, warmup_factor 0.0005434782608695652
Traceback (most recent call last):
  File "../../train.py", line 527, in <module>
    cli_main()
  File "../../train.py", line 520, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/workspace/OFA/fairseq/fairseq/distributed/utils.py", line 374, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/workspace/OFA/fairseq/fairseq/distributed/utils.py", line 348, in distributed_main
    main(cfg, **kwargs)
  File "../../train.py", line 189, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/opt/conda/envs/OFA/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "../../train.py", line 300, in train
    log_output = trainer.train_step(samples)
  File "/opt/conda/envs/OFA/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/workspace/OFA/trainer.py", line 806, in train_step
    raise e
  File "/workspace/OFA/trainer.py", line 780, in train_step
    **extra_kwargs,
  File "/workspace/OFA/tasks/ofa_task.py", line 319, in train_step
    loss, sample_size, logging_output = criterion(model, sample, update_num=update_num)
  File "/opt/conda/envs/OFA/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/OFA/criterions/label_smoothed_cross_entropy.py", line 200, in forward
    loss, nll_loss, ntokens = self.compute_loss(model, net_output, sample, update_num, reduce=reduce)
  File "/workspace/OFA/criterions/label_smoothed_cross_entropy.py", line 245, in compute_loss
    lprobs, target, constraint_masks = self.get_lprobs_and_target(model, net_output, sample)
  File "/workspace/OFA/criterions/label_smoothed_cross_entropy.py", line 222, in get_lprobs_and_target
    net_output[0].masked_fill_(~constraint_masks, -math.inf)
RuntimeError: Output 0 of _DDPSinkBackward is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.
```
How can I solve it? 
I will really appreciate it!

**Comment by JustinLin610** [comment]
Is the version of Pytorch that you use higher than 1.8, like 1.10? We recently found this problem in Pytorch 1.10. You can try changing the in-place operation of masked fill to out-of-place operation. Just try:
```
net_output = list(net_output)
net_output[0] = net_output[0].masked_fill(~constraint_masks, -math.inf)
```
and see if it works.

**Comment by dannyxiaocn** [comment]
Yeah, thank you so much!! It's the version problem, the 1.9 also works. But even if I replace the code in label_smoothed_cross_entropy.py as you mentioned in 1.10.2, it still not works.
