### ISSUE TITLE
Unsuccessful Image Caption step 2 fine-tuning

### ISSUE THREAD

**Issue by dannyxiaocn** [OFA-Sys/OFA#28]
Hi, when running the `train_caption_stage2.sh`, it triggers a AssertError like: 
```
Traceback (most recent call last):
  File "../../train.py", line 527, in <module>
    cli_main()
  File "../../train.py", line 520, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/workspace/OFA/fairseq/fairseq/distributed/utils.py", line 374, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/workspace/OFA/fairseq/fairseq/distributed/utils.py", line 348, in distributed_main
    main(cfg, **kwargs)
  File "../../train.py", line 189, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "../../train.py", line 300, in train
    log_output = trainer.train_step(samples)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/OFA/trainer.py", line 773, in train_step
    loss, sample_size_i, logging_output = self.task.train_step(
  File "/workspace/OFA/tasks/ofa_task.py", line 319, in train_step
    loss, sample_size, logging_output = criterion(model, sample, update_num=update_num)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 881, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/OFA/criterions/scst_loss.py", line 88, in forward
    loss, score, ntokens, nsentences = self.compute_loss(model, sample, reduce=reduce)
  File "/workspace/OFA/criterions/scst_loss.py", line 239, in compute_loss
    gen_target, gen_res, gt_res = self.get_generator_out(model, sample)
  File "/workspace/OFA/criterions/scst_loss.py", line 149, in get_generator_out
    gen_out = self.task.scst_generator.generate([model], sample)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/OFA/models/sequence_generator.py", line 207, in generate
    return self._generate(models, sample, **kwargs)
  File "/workspace/OFA/models/sequence_generator.py", line 480, in _generate
    assert step < max_len, f"{step} < {max_len}"
AssertionError: 16 < 16
```
How can I fix this problem? Thx!

**Comment by logicwong** [comment]
CIDEr optimization is unstable and requires careful hyperparameter tuning. The error is generally caused by two reasons: 
1. The batch size is too small, which affects the stability of resnet batch normalization;
2. The learning rate is too large, resulting in unstable training;

It is recommended that you can increase the batch size or reduce the learning rate. If neither of these methods works, you can directly use --freeze-resnet to freeze the inner states of batch normalization.

**Comment by dannyxiaocn** [comment]
I have set --freeze-resnet in the `train_caption_stage2.sh` but it still triggers this Error. My file is as follows:
```
```

**Comment by logicwong** [comment]
Try changing `for lr in {1e-5,}; do` to `for lr in {5e-6,}; do` ?

**Comment by dannyxiaocn** [comment]
Nah, it doesn't work 😩

**Comment by logicwong** [comment]
Wait a moment, I will run your script and give you feedback as soon as possible.

**Comment by logicwong** [comment]
I have encountered an OOM error with `batch_size=4`（running on 4 NVIDIA-V100 GPUs with 32GB memory). Are you using GPUs with larger memory?
Anyway, I use the command below and it works fine (just modified `batch_size=2` and `update_freq=8` in your command and use my own `caption_stage1_best.pt`). I suspect the quality of `caption_stage1_best.pt` will also affect the hyperparameter of stage2 finetuning. I provide my `caption_stage1_best.pt` here ([Link](https://ofa-beijing.oss-cn-beijing.aliyuncs.com/checkpoints/checkpoint_stage1_best.pt), ~139.5 CIDEr) that you can use it for stage2 fine-tuning.
In addition, I'm curious about the CIDEr score of your `caption_stage1_best.pt`, and have you tried a smaller learning rate (like 1e-6)? Looking forward to your feedback.

My training script:
```
#!/usr/bin/env

# The port for communication. Note that if you want to run multiple tasks on the same machine,
# you need to specify different port numbers.
export MASTER_PORT=1052

log_dir=./stage2_logs
save_dir=./stage2_checkpoints
mkdir -p $log_dir $save_dir

bpe_dir=../../utils/BPE
user_dir=../../ofa_module

data_dir=../../dataset/caption_data
data=${data_dir}/caption_stage2_train.tsv,${data_dir}/caption_val.tsv
restore_file=../../checkpoints/caption_stage1_best.pt
selected_cols=1,4,2

task=caption
arch=ofa_large
criterion=scst_reward_criterion
label_smoothing=0.1
lr=1e-7
max_epoch=5
warmup_ratio=0.06
batch_size=2
update_freq=8
resnet_drop_path_rate=0.0
encoder_drop_path_rate=0.0
decoder_drop_path_rate=0.0
dropout=0.0
attention_dropout=0.0
max_src_length=80
max_tgt_length=20
num_bins=1000
patch_image_size=480
eval_cider_cached=${data_dir}/cider_cached_tokens/coco-valid-words.p
scst_cider_cached=${data_dir}/cider_cached_tokens/coco-train-words.p

for lr in {1e-5,}; do
  echo "lr "${lr}
  for max_epoch in {3,}; do
    echo "max_epoch "${max_epoch}

    log_file=${log_dir}/${lr}"_"${max_epoch}".log"
    save_path=${save_dir}/${lr}"_"${max_epoch}
    mkdir -p $save_path

    CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --nproc_per_node=4 --master_port=${MASTER_PORT} ../../train.py \
        $data \
        --selected-cols=${selected_cols} \
        --bpe-dir=${bpe_dir} \
        --user-dir=${user_dir} \
        --restore-file=${restore_file} \
        --reset-optimizer --reset-dataloader --reset-meters \
        --save-dir=${save_path} \
        --task=${task} \
        --arch=${arch} \
        --criterion=${criterion} \
        --batch-size=${batch_size} \
        --update-freq=${update_freq} \
        --encoder-normalize-before \
        --decoder-normalize-before \
        --share-decoder-input-output-embed \
        --share-all-embeddings \
        --layernorm-embedding \
        --patch-layernorm-embedding \
        --code-layernorm-embedding \
        --resnet-drop-path-rate=${resnet_drop_path_rate} \
        --encoder-drop-path-rate=${encoder_drop_path_rate} \
        --decoder-drop-path-rate=${decoder_drop_path_rate} \
        --dropout=${dropout} \
        --attention-dropout=${attention_dropout} \
        --weight-decay=0.01 --optimizer=adam --adam-betas="(0.9,0.999)" --adam-eps=1e-08 --clip-norm=1.0 \
        --lr-scheduler=polynomial_decay --lr=${lr} --end-learning-rate=2e-7 \
        --max-epoch=${max_epoch} --warmup-ratio=${warmup_ratio} \
        --log-format=simple --log-interval=10 \
        --fixed-validation-seed=7 \
        --no-epoch-checkpoints --keep-best-checkpoints=1 \
        --save-interval=1 --validate-interval=1 \
        --save-interval-updates=500 --validate-interval-updates=500 \
        --eval-cider \
        --eval-cider-cached-tokens=${eval_cider_cached} \
        --eval-args='{"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}' \
        --best-checkpoint-metric=cider --maximize-best-checkpoint-metric \
        --max-src-length=${max_src_length} \
        --max-tgt-length=${max_tgt_length} \
        --find-unused-parameters \
        --freeze-encoder-embedding \
        --freeze-decoder-embedding \
				--freeze-resnet \
        --add-type-embedding \
        --scale-attn \
        --scale-fc \
        --scale-heads \
        --disable-entangle \
        --num-bins=${num_bins} \
        --patch-image-size=${patch_image_size} \
        --scst \
        --scst-cider-cached-tokens=${scst_cider_cached} \
        --scst-args='{"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}' \
        --memory-efficient-fp16 \
        --fp16-scale-window=512 \
        --num-workers=0 > ${log_file} 2>&1
  done
done
```

My training logs:
```
2022-03-06 00:20:57 - progress_bar.py[line:274] - INFO: epoch 001:     10 / 1771 loss=-0.003, score=1.446, ntokens=3522.2, nsentences=320, sample_size=3522.2, wps=290.5, ups=0.08, wpb=3522.2, bsz=320, num_updates=10, lr=3.14465e-07, gnorm=0.487, clip=0, loss_scale=128, train_wall=123, gb_free=3.5, wall=137
2022-03-06 00:22:58 - progress_bar.py[line:274] - INFO: epoch 001:     20 / 1771 loss=-0.006, score=1.394, ntokens=3482.8, nsentences=320, sample_size=3482.8, wps=288.2, ups=0.08, wpb=3482.8, bsz=320, num_updates=20, lr=6.28931e-07, gnorm=0.534, clip=0, loss_scale=128, train_wall=121, gb_free=3.6, wall=258
2022-03-06 00:24:59 - progress_bar.py[line:274] - INFO: epoch 001:     30 / 1771 loss=-0.007, score=1.491, ntokens=3491.1, nsentences=320, sample_size=3491.1, wps=288.4, ups=0.08, wpb=3491.1, bsz=320, num_updates=30, lr=9.43396e-07, gnorm=0.563, clip=0, loss_scale=128, train_wall=121, gb_free=3.6, wall=379
2022-03-06 00:27:00 - progress_bar.py[line:274] - INFO: epoch 001:     40 / 1771 loss=-0.006, score=1.464, ntokens=3503.7, nsentences=320, sample_size=3503.7, wps=289.2, ups=0.08, wpb=3503.7, bsz=320, num_updates=40, lr=1.25786e-06, gnorm=0.566, clip=0, loss_scale=128, train_wall=121, gb_free=3.5, wall=500
2022-03-06 00:29:01 - progress_bar.py[line:274] - INFO: epoch 001:     50 / 1771 loss=-0.006, score=1.525, ntokens=3507.3, nsentences=320, sample_size=3507.3, wps=289.6, ups=0.08, wpb=3507.3, bsz=320, num_updates=50, lr=1.57233e-06, gnorm=0.576, clip=0, loss_scale=128, train_wall=121, gb_free=3.6, wall=621
2022-03-06 00:31:02 - progress_bar.py[line:274] - INFO: epoch 001:     60 / 1771 loss=-0.006, score=1.466, ntokens=3508.2, nsentences=320, sample_size=3508.2, wps=290, ups=0.08, wpb=3508.2, bsz=320, num_updates=60, lr=1.88679e-06, gnorm=0.578, clip=0, loss_scale=128, train_wall=121, gb_free=3.6, wall=742
2022-03-06 00:33:04 - progress_bar.py[line:274] - INFO: epoch 001:     70 / 1771 loss=-0.006, score=1.397, ntokens=3523.4, nsentences=320, sample_size=3523.4, wps=290.3, ups=0.08, wpb=3523.4, bsz=320, num_updates=70, lr=2.20126e-06, gnorm=0.545, clip=0, loss_scale=128, train_wall=121, gb_free=3.6, wall=863
2022-03-06 00:35:05 - progress_bar.py[line:274] - INFO: epoch 001:     80 / 1771 loss=-0.005, score=1.436, ntokens=3510, nsentences=320, sample_size=3510, wps=290.1, ups=0.08, wpb=3510, bsz=320, num_updates=80, lr=2.51572e-06, gnorm=0.489, clip=0, loss_scale=128, train_wall=121, gb_free=3.5, wall=984
2022-03-06 00:37:05 - progress_bar.py[line:274] - INFO: epoch 001:     90 / 1771 loss=-0.006, score=1.445, ntokens=3488.5, nsentences=320, sample_size=3488.5, wps=289.6, ups=0.08, wpb=3488.5, bsz=320, num_updates=90, lr=2.83019e-06, gnorm=0.553, clip=0, loss_scale=128, train_wall=120, gb_free=3.5, wall=1105
2022-03-06 00:39:06 - progress_bar.py[line:274] - INFO: epoch 001:    100 / 1771 loss=-0.005, score=1.437, ntokens=3505.1, nsentences=320, sample_size=3505.1, wps=289.8, ups=0.08, wpb=3505.1, bsz=320, num_updates=100, lr=3.14465e-06, gnorm=0.575, clip=0, loss_scale=128, train_wall=121, gb_free=3.6, wall=1226
2022-03-06 00:41:07 - progress_bar.py[line:274] - INFO: epoch 001:    110 / 1771 loss=-0.005, score=1.413, ntokens=3525.9, nsentences=320, sample_size=3525.9, wps=291.8, ups=0.08, wpb=3525.9, bsz=320, num_updates=110, lr=3.45912e-06, gnorm=0.502, clip=0, loss_scale=128, train_wall=121, gb_free=3.6, wall=1347
2022-03-06 00:43:08 - progress_bar.py[line:274] - INFO: epoch 001:    120 / 1771 loss=-0.006, score=1.493, ntokens=3505.9, nsentences=320, sample_size=3505.9, wps=289.6, ups=0.08, wpb=3505.9, bsz=320, num_updates=120, lr=3.77358e-06, gnorm=0.559, clip=0, loss_scale=128, train_wall=121, gb_free=3.6, wall=1468
2022-03-06 00:45:09 - progress_bar.py[line:274] - INFO: epoch 001:    130 / 1771 loss=-0.006, score=1.452, ntokens=3507.4, nsentences=320, sample_size=3507.4, wps=289.8, ups=0.08, wpb=3507.4, bsz=320, num_updates=130, lr=4.08805e-06, gnorm=0.58, clip=0, loss_scale=128, train_wall=121, gb_free=3.5, wall=1589
2022-03-06 00:47:10 - progress_bar.py[line:274] - INFO: epoch 001:    140 / 1771 loss=-0.006, score=1.47, ntokens=3498.4, nsentences=320, sample_size=3498.4, wps=288, ups=0.08, wpb=3498.4, bsz=320, num_updates=140, lr=4.40252e-06, gnorm=0.557, clip=10, loss_scale=128, train_wall=121, gb_free=3.5, wall=1710
2022-03-06 00:49:11 - progress_bar.py[line:274] - INFO: epoch 001:    150 / 1771 loss=-0.005, score=1.477, ntokens=3501.1, nsentences=320, sample_size=3501.1, wps=289.7, ups=0.08, wpb=3501.1, bsz=320, num_updates=150, lr=4.71698e-06, gnorm=0.611, clip=10, loss_scale=128, train_wall=121, gb_free=3.5, wall=1831
2022-03-06 00:51:12 - progress_bar.py[line:274] - INFO: epoch 001:    160 / 1771 loss=-0.007, score=1.448, ntokens=3508.7, nsentences=320, sample_size=3508.7, wps=289.9, ups=0.08, wpb=3508.7, bsz=320, num_updates=160, lr=5.03145e-06, gnorm=0.532, clip=0, loss_scale=128, train_wall=121, gb_free=3.5, wall=1952
2022-03-06 00:53:13 - progress_bar.py[line:274] - INFO: epoch 001:    170 / 1771 loss=-0.006, score=1.464, ntokens=3513.5, nsentences=320, sample_size=3513.5, wps=290, ups=0.08, wpb=3513.5, bsz=320, num_updates=170, lr=5.34591e-06, gnorm=0.564, clip=0, loss_scale=128, train_wall=121, gb_free=3.6, wall=2073
2022-03-06 00:55:15 - progress_bar.py[line:274] - INFO: epoch 001:    180 / 1771 loss=-0.006, score=1.478, ntokens=3515.6, nsentences=320, sample_size=3515.6, wps=289.3, ups=0.08, wpb=3515.6, bsz=320, num_updates=180, lr=5.66038e-06, gnorm=0.602, clip=0, loss_scale=128, train_wall=121, gb_free=3.6, wall=2195
2022-03-06 00:57:16 - progress_bar.py[line:274] - INFO: epoch 001:    190 / 1771 loss=-0.006, score=1.483, ntokens=3517.5, nsentences=320, sample_size=3517.5, wps=290.9, ups=0.08, wpb=3517.5, bsz=320, num_updates=190, lr=5.97484e-06, gnorm=0.474, clip=0, loss_scale=128, train_wall=121, gb_free=3.6, wall=2316
2022-03-06 00:59:17 - progress_bar.py[line:274] - INFO: epoch 001:    200 / 1771 loss=-0.006, score=1.559, ntokens=3529.6, nsentences=320, sample_size=3529.6, wps=291.5, ups=0.08, wpb=3529.6, bsz=320, num_updates=200, lr=6.28931e-06, gnorm=0.544, clip=0, loss_scale=128, train_wall=121, gb_free=3.5, wall=2437
2022-03-06 01:01:18 - progress_bar.py[line:274] - INFO: epoch 001:    210 / 1771 loss=-0.006, score=1.475, ntokens=3511.1, nsentences=320, sample_size=3511.1, wps=290.4, ups=0.08, wpb=3511.1, bsz=320, num_updates=210, lr=6.60377e-06, gnorm=0.486, clip=0, loss_scale=128, train_wall=121, gb_free=3.5, wall=2558
2022-03-06 01:03:19 - progress_bar.py[line:274] - INFO: epoch 001:    220 / 1771 loss=-0.006, score=1.45, ntokens=3532.6, nsentences=320, sample_size=3532.6, wps=291.3, ups=0.08, wpb=3532.6, bsz=320, num_updates=220, lr=6.91824e-06, gnorm=0.545, clip=0, loss_scale=128, train_wall=121, gb_free=3.5, wall=2679
2022-03-06 01:05:21 - progress_bar.py[line:274] - INFO: epoch 001:    230 / 1771 loss=-0.005, score=1.555, ntokens=3537.2, nsentences=320, sample_size=3537.2, wps=291.3, ups=0.08, wpb=3537.2, bsz=320, num_updates=230, lr=7.2327e-06, gnorm=0.565, clip=0, loss_scale=128, train_wall=121, gb_free=3.5, wall=2800
2022-03-06 01:07:21 - progress_bar.py[line:274] - INFO: epoch 001:    240 / 1771 loss=-0.006, score=1.461, ntokens=3527.9, nsentences=320, sample_size=3527.9, wps=291.8, ups=0.08, wpb=3527.9, bsz=320, num_updates=240, lr=7.54717e-06, gnorm=0.525, clip=0, loss_scale=128, train_wall=121, gb_free=3.5, wall=2921
2022-03-06 01:09:23 - progress_bar.py[line:274] - INFO: epoch 001:    250 / 1771 loss=-0.006, score=1.469, ntokens=3520.4, nsentences=320, sample_size=3520.4, wps=290.8, ups=0.08, wpb=3520.4, bsz=320, num_updates=250, lr=7.86164e-06, gnorm=0.519, clip=0, loss_scale=128, train_wall=121, gb_free=3.5, wall=3042
2022-03-06 01:11:24 - progress_bar.py[line:274] - INFO: epoch 001:    260 / 1771 loss=-0.005, score=1.485, ntokens=3546.1, nsentences=320, sample_size=3546.1, wps=291.2, ups=0.08, wpb=3546.1, bsz=320, num_updates=260, lr=8.1761e-06, gnorm=0.589, clip=0, loss_scale=128, train_wall=122, gb_free=3.5, wall=3164
2022-03-06 01:13:26 - progress_bar.py[line:274] - INFO: epoch 001:    270 / 1771 loss=-0.004, score=1.518, ntokens=3549, nsentences=320, sample_size=3549, wps=291.8, ups=0.08, wpb=3549, bsz=320, num_updates=270, lr=8.49057e-06, gnorm=0.594, clip=0, loss_scale=128, train_wall=122, gb_free=3.5, wall=3286
2022-03-06 01:15:27 - progress_bar.py[line:274] - INFO: epoch 001:    280 / 1771 loss=-0.006, score=1.465, ntokens=3528.5, nsentences=320, sample_size=3528.5, wps=291.4, ups=0.08, wpb=3528.5, bsz=320, num_updates=280, lr=8.80503e-06, gnorm=0.553, clip=0, loss_scale=128, train_wall=121, gb_free=3.5, wall=3407
2022-03-06 01:17:28 - progress_bar.py[line:274] - INFO: epoch 001:    290 / 1771 loss=-0.006, score=1.532, ntokens=3548.3, nsentences=320, sample_size=3548.3, wps=292.9, ups=0.08, wpb=3548.3, bsz=320, num_updates=290, lr=9.1195e-06, gnorm=0.552, clip=0, loss_scale=128, train_wall=121, gb_free=3.5, wall=3528
2022-03-06 01:19:29 - progress_bar.py[line:274] - INFO: epoch 001:    300 / 1771 loss=-0.007, score=1.506, ntokens=3534.1, nsentences=320, sample_size=3534.1, wps=291.4, ups=0.08, wpb=3534.1, bsz=320, num_updates=300, lr=9.43396e-06, gnorm=0.543, clip=0, loss_scale=128, train_wall=121, gb_free=3.5, wall=3649
2022-03-06 01:21:31 - progress_bar.py[line:274] - INFO: epoch 001:    310 / 1771 loss=-0.005, score=1.519, ntokens=3577.1, nsentences=320, sample_size=3577.1, wps=294.8, ups=0.08, wpb=3577.1, bsz=320, num_updates=310, lr=9.74843e-06, gnorm=0.554, clip=0, loss_scale=128, train_wall=121, gb_free=3.5, wall=3771
2022-03-06 01:23:33 - progress_bar.py[line:274] - INFO: epoch 001:    320 / 1771 loss=-0.006, score=1.528, ntokens=3595.3, nsentences=320, sample_size=3595.3, wps=294.6, ups=0.08, wpb=3595.3, bsz=320, num_updates=320, lr=9.99608e-06, gnorm=0.594, clip=0, loss_scale=128, train_wall=122, gb_free=3.6, wall=3893
2022-03-06 01:25:35 - progress_bar.py[line:274] - INFO: epoch 001:    330 / 1771 loss=-0.006, score=1.484, ntokens=3628.8, nsentences=320, sample_size=3628.8, wps=296.9, ups=0.08, wpb=3628.8, bsz=320, num_updates=330, lr=9.97646e-06, gnorm=0.528, clip=0, loss_scale=128, train_wall=122, gb_free=3.6, wall=4015
2022-03-06 01:27:37 - progress_bar.py[line:274] - INFO: epoch 001:    340 / 1771 loss=-0.005, score=1.547, ntokens=3617.3, nsentences=320, sample_size=3617.3, wps=296.3, ups=0.08, wpb=3617.3, bsz=320, num_updates=340, lr=9.95684e-06, gnorm=0.637, clip=10, loss_scale=128, train_wall=122, gb_free=3.5, wall=4137
2022-03-06 01:29:39 - progress_bar.py[line:274] - INFO: epoch 001:    350 / 1771 loss=-0.005, score=1.534, ntokens=3611.1, nsentences=320, sample_size=3611.1, wps=295.8, ups=0.08, wpb=3611.1, bsz=320, num_updates=350, lr=9.93722e-06, gnorm=0.507, clip=0, loss_scale=128, train_wall=122, gb_free=3.5, wall=4259
2022-03-06 01:31:41 - progress_bar.py[line:274] - INFO: epoch 001:    360 / 1771 loss=-0.005, score=1.497, ntokens=3596.6, nsentences=320, sample_size=3596.6, wps=294.9, ups=0.08, wpb=3596.6, bsz=320, num_updates=360, lr=9.9176e-06, gnorm=0.565, clip=0, loss_scale=128, train_wall=122, gb_free=3.5, wall=4381
2022-03-06 01:33:44 - progress_bar.py[line:274] - INFO: epoch 001:    370 / 1771 loss=-0.007, score=1.464, ntokens=3621.6, nsentences=320, sample_size=3621.6, wps=295.6, ups=0.08, wpb=3621.6, bsz=320, num_updates=370, lr=9.89798e-06, gnorm=0.534, clip=0, loss_scale=128, train_wall=122, gb_free=3.5, wall=4503
2022-03-06 01:35:46 - progress_bar.py[line:274] - INFO: epoch 001:    380 / 1771 loss=-0.006, score=1.537, ntokens=3606.7, nsentences=320, sample_size=3606.7, wps=295.2, ups=0.08, wpb=3606.7, bsz=320, num_updates=380, lr=9.87836e-06, gnorm=0.54, clip=0, loss_scale=128, train_wall=122, gb_free=3.5, wall=4626
2022-03-06 01:37:48 - progress_bar.py[line:274] - INFO: epoch 001:    390 / 1771 loss=-0.005, score=1.475, ntokens=3618.4, nsentences=320, sample_size=3618.4, wps=295.9, ups=0.08, wpb=3618.4, bsz=320, num_updates=390, lr=9.85874e-06, gnorm=0.561, clip=0, loss_scale=128, train_wall=122, gb_free=3.5, wall=4748
2022-03-06 01:39:51 - progress_bar.py[line:274] - INFO: epoch 001:    400 / 1771 loss=-0.006, score=1.515, ntokens=3638.9, nsentences=320, sample_size=3638.9, wps=296.8, ups=0.08, wpb=3638.9, bsz=320, num_updates=400, lr=9.83912e-06, gnorm=0.56, clip=0, loss_scale=128, train_wall=122, gb_free=3.5, wall=4870
2022-03-06 01:41:52 - progress_bar.py[line:274] - INFO: epoch 001:    410 / 1771 loss=-0.005, score=1.513, ntokens=3585, nsentences=320, sample_size=3585, wps=295.2, ups=0.08, wpb=3585, bsz=320, num_updates=410, lr=9.8195e-06, gnorm=0.488, clip=0, loss_scale=128, train_wall=121, gb_free=3.5, wall=4992
2022-03-06 01:43:54 - progress_bar.py[line:274] - INFO: epoch 001:    420 / 1771 loss=-0.006, score=1.559, ntokens=3568.9, nsentences=320, sample_size=3568.9, wps=292.9, ups=0.08, wpb=3568.9, bsz=320, num_updates=420, lr=9.79988e-06, gnorm=0.506, clip=0, loss_scale=128, train_wall=122, gb_free=3.5, wall=5114
2022-03-06 01:45:56 - progress_bar.py[line:274] - INFO: epoch 001:    430 / 1771 loss=-0.005, score=1.483, ntokens=3569.7, nsentences=320, sample_size=3569.7, wps=293.3, ups=0.08, wpb=3569.7, bsz=320, num_updates=430, lr=9.78026e-06, gnorm=0.627, clip=0, loss_scale=128, train_wall=122, gb_free=3.6, wall=5235
2022-03-06 01:47:57 - progress_bar.py[line:274] - INFO: epoch 001:    440 / 1771 loss=-0.006, score=1.533, ntokens=3524.3, nsentences=320, sample_size=3524.3, wps=289.6, ups=0.08, wpb=3524.3, bsz=320, num_updates=440, lr=9.76064e-06, gnorm=0.561, clip=0, loss_scale=128, train_wall=122, gb_free=3.5, wall=5357
2022-03-06 01:49:58 - progress_bar.py[line:274] - INFO: epoch 001:    450 / 1771 loss=-0.005, score=1.456, ntokens=3517, nsentences=320, sample_size=3517, wps=290.8, ups=0.08, wpb=3517, bsz=320, num_updates=450, lr=9.74102e-06, gnorm=0.563, clip=0, loss_scale=128, train_wall=121, gb_free=3.5, wall=5478
2022-03-06 01:52:00 - progress_bar.py[line:274] - INFO: epoch 001:    460 / 1771 loss=-0.006, score=1.495, ntokens=3532.4, nsentences=320, sample_size=3532.4, wps=290.1, ups=0.08, wpb=3532.4, bsz=320, num_updates=460, lr=9.7214e-06, gnorm=0.531, clip=0, loss_scale=128, train_wall=122, gb_free=3.5, wall=5600
2022-03-06 01:54:01 - progress_bar.py[line:274] - INFO: epoch 001:    470 / 1771 loss=-0.006, score=1.491, ntokens=3535.5, nsentences=320, sample_size=3535.5, wps=291.3, ups=0.08, wpb=3535.5, bsz=320, num_updates=470, lr=9.70178e-06, gnorm=0.593, clip=0, loss_scale=128, train_wall=121, gb_free=3.5, wall=5721
2022-03-06 01:56:02 - progress_bar.py[line:274] - INFO: epoch 001:    480 / 1771 loss=-0.007, score=1.528, ntokens=3546.5, nsentences=320, sample_size=3546.5, wps=293.5, ups=0.08, wpb=3546.5, bsz=320, num_updates=480, lr=9.68216e-06, gnorm=0.581, clip=10, loss_scale=128, train_wall=121, gb_free=3.5, wall=5842
2022-03-06 01:58:03 - progress_bar.py[line:274] - INFO: epoch 001:    490 / 1771 loss=-0.006, score=1.513, ntokens=3539.5, nsentences=320, sample_size=3539.5, wps=292.7, ups=0.08, wpb=3539.5, bsz=320, num_updates=490, lr=9.66254e-06, gnorm=0.524, clip=0, loss_scale=128, train_wall=121, gb_free=3.5, wall=5963
2022-03-06 02:00:04 - progress_bar.py[line:274] - INFO: epoch 001:    500 / 1771 loss=-0.005, score=1.547, ntokens=3518.8, nsentences=320, sample_size=3518.8, wps=290.5, ups=0.08, wpb=3518.8, bsz=320, num_updates=500, lr=9.64292e-06, gnorm=0.548, clip=0, loss_scale=128, train_wall=121, gb_free=3.5, wall=6084
2022-03-06 02:00:04 - train.py[line:435] - INFO: begin validation on "valid" subset
slice_id 0 seek offset 0
slice_id 1 seek offset 1250
slice_id 2 seek offset 2500
slice_id 3 seek offset 3750
slice_id 0 seek offset 0
slice_id 1 seek offset 1250
slice_id 3 seek offset 3750
slice_id 2 seek offset 2500
2022-03-06 02:13:56 - progress_bar.py[line:282] - INFO: epoch 001 | valid on 'valid' subset | loss -0.005 | score 1.35 | ntokens 441.746 | nsentences 40 | sample_size 441.746 | cider 1.45 | wps 332 | wpb 441.7 | bsz 40 | num_updates 500
2022-03-06 02:13:56 - checkpoint_utils.py[line:64] - INFO: Preparing to save checkpoint for epoch 1 @ 500 updates
2022-03-06 02:13:56 - trainer.py[line:431] - INFO: Saving checkpoint to ./stage2_checkpoints/1e-5_3/checkpoint_1_500.pt
2022-03-06 02:14:06 - trainer.py[line:441] - INFO: Finished saving checkpoint to ./stage2_checkpoints/1e-5_3/checkpoint_1_500.pt
2022-03-06 02:14:22 - checkpoint_utils.py[line:135] - INFO: Saved checkpoint ./stage2_checkpoints/1e-5_3/checkpoint_1_500.pt (epoch 1 @ 500 updates, score 1.45) (writing took 26.15961988386698 seconds)

```

**Comment by dannyxiaocn** [comment]
Thank you for your response. Unfortunately, my gpu has only 24GB memory. My CIDEr score is 136.7, with an early stopping. So I think it's probably the problem of best checkpoint of stage1. I will download yours and try it out :)

**Comment by logicwong** [comment]
I'm still confused because 24GB memory is not enough to use `batch_size=4` for stage2 finetuning. But in your file, you do use `batch_size=4`. Can you check if this file is actually used for training?

<img width="826" alt="298E99EC-6F58-4C5B-8462-9081B3DB492C" src="https://user-images.githubusercontent.com/36780733/156908371-d1a3d56d-2b8e-46b4-9a5b-22c11e1ffbe9.png">

**Comment by dannyxiaocn** [comment]
You are brilliant! The problem is the stored checkpoint from stage 1 has a mismatched name. That's the reason why it has that Error. It even didn't reach the data part! After I change the name to be matched, the stage2 fine-tuning is running! Thank you so much!
