### ISSUE TITLE
How to evaluate prompt tuning model?

### ISSUE THREAD

**Issue by flymark2010** [OFA-Sys/OFA#313]
Hi, OFA team,

I have used prompt tuning method to train a vqa-gen task, and evaluate the model via `run_scripts/vqa/evaluate_vqa_beam.sh` directly, but got error below:

```
Traceback (most recent call last):
  File "../../evaluate.py", line 160, in <module>
    cli_main()
  File "../../evaluate.py", line 154, in cli_main
    distributed_utils.call_main(
  File "/workspace/project/OFA/fairseq/fairseq/distributed/utils.py", line 376, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/workspace/project/OFA/fairseq/fairseq/distributed/utils.py", line 350, in distributed_main
    main(cfg, **kwargs)
  File "../../evaluate.py", line 138, in main
    result, scores = eval_step(task, generator, models, sample, **kwargs)
  File "/workspace/project/OFA/utils/eval_utils.py", line 306, in eval_step
    return eval_vqa_gen(task, generator, models, sample, **kwargs)
  File "/workspace/project/OFA/utils/eval_utils.py", line 47, in eval_vqa_gen
    hypos = task.inference_step(generator, models, sample, prefix_tokens=sample['prefix_tokens'])
  File "/workspace/project/OFA/fairseq/fairseq/tasks/fairseq_task.py", line 517, in inference_step
    return generator.generate(
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/project/OFA/models/sequence_generator.py", line 209, in generate
    return self._generate(models, sample, **kwargs)
  File "/workspace/project/OFA/models/sequence_generator.py", line 354, in _generate
    lprobs, avg_attn_scores = model.forward_decoder(
  File "/workspace/project/OFA/models/sequence_generator.py", line 824, in forward_decoder
    decoder_out = model.decoder.forward(
  File "/workspace/project/OFA/models/ofa/unify_transformer.py", line 1343, in forward
    x, extra = self.extract_features(
  File "/workspace/project/OFA/models/ofa/unify_transformer.py", line 1367, in extract_features
    return self.extract_features_scriptable(
  File "/workspace/project/OFA/models/ofa/unify_transformer.py", line 1532, in extract_features_scriptable
    x, layer_attn, _ = layer(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/project/OFA/models/ofa/unify_transformer_layer.py", line 500, in forward
    x, attn = self.self_attn(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/project/OFA/models/ofa/unify_multihead_attention.py", line 342, in forward
    assert key_padding_mask.size(1) == k.size(1), "{} vs {}".format(
AssertionError: 101 vs 102
```

Could you please provide an example for evaluating prompt tuning models, thanks?

**Comment by yh351016** [comment]
@flymark2010  Hi, flymar，can you also share the script for evaluating it as well? I wonder the hyperparameters you used for evaluating it seems not so good.

**Comment by 0xpause** [comment]
No hyperparameters were modified. Here is the scritpt:

```
#!/usr/bin/env bash

# The port for communication. Note that if you want to run multiple tasks on the same machine,
# you need to specify different port numbers.
export MASTER_PORT=8082

user_dir=../../ofa_module
bpe_dir=../../utils/BPE

# val or test
split=val

task=vqa_gen

data=../../dataset/fire_data/val_2k.tsv
ans2label_file=../../dataset/fire_data/trainval_ans2label.pkl
path=vqa_prompt_checkpoints/40000_1000_4e-5_480/checkpoint_best.pt
result_path=results
selected_cols=0,1,2,3,4

CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nproc_per_node=4 --master_port=${MASTER_PORT} ../../evaluate.py \
    ${data} \
    --path=${path} \
    --user-dir=${user_dir} \
    --task=${task} \
    --batch-size=16 \
    --log-format=simple --log-interval=10 \
    --seed=7 \
    --gen-subset=${split} \
    --results-path=${result_path} \
    --fp16 \
    --ema-eval \
    --beam-search-vqa-eval \
    --beam=5 \
    --unnormalized \
    --temperature=1.0 \
    --num-workers=0 \
    --model-overrides="{\"data\":\"${data}\",\"bpe_dir\":\"${bpe_dir}\",\"selected_cols\":\"${selected_cols}\",\"ans2label_file\":\"${ans2label_file}\"}"
```

**Comment by flymark2010** [comment]
@yh351016 No hyperparameters were modified. Here is the scritpt:

```
#!/usr/bin/env bash

# The port for communication. Note that if you want to run multiple tasks on the same machine,
# you need to specify different port numbers.
export MASTER_PORT=8082

user_dir=../../ofa_module
bpe_dir=../../utils/BPE

# val or test
split=val

task=vqa_gen

data=../../dataset/fire_data/val_2k.tsv
ans2label_file=../../dataset/fire_data/trainval_ans2label.pkl
path=vqa_prompt_checkpoints/40000_1000_4e-5_480/checkpoint_best.pt
result_path=results
selected_cols=0,1,2,3,4

CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nproc_per_node=4 --master_port=${MASTER_PORT} ../../evaluate.py \
    ${data} \
    --path=${path} \
    --user-dir=${user_dir} \
    --task=${task} \
    --batch-size=16 \
    --log-format=simple --log-interval=10 \
    --seed=7 \
    --gen-subset=${split} \
    --results-path=${result_path} \
    --fp16 \
    --ema-eval \
    --beam-search-vqa-eval \
    --beam=5 \
    --unnormalized \
    --temperature=1.0 \
    --num-workers=0 \
    --model-overrides="{\"data\":\"${data}\",\"bpe_dir\":\"${bpe_dir}\",\"selected_cols\":\"${selected_cols}\",\"ans2label_file\":\"${ans2label_file}\"}"
```

**Comment by yh351016** [comment]
@flymark2010    Evaluating config needs to be consistent with the training config,as follows:
       prompt_type_method=prefix
       encoder_prompt_length=$(raining prompt_length)
       decoder_prompt_length=$(raining prompt_length)
   
      --encoder-prompt \
      --decoder-prompt \
      --encoder-prompt-type=${prompt_type_method} \
      --decoder-prompt-type=${prompt_type_method} \
      --encoder-prompt-length=${encoder_prompt_length} \
      --decoder-prompt-length=${decoder_prompt_length} \

**Comment by flymark2010** [comment]
@yh351016 The `evaluate.py` does not support these argments.

```
...
evaluate.py: error: unrecognized arguments: --encoder-prompt --decoder-prompt --encoder-prompt-type=prefix --decoder-prompt-type=prefix --encoder-prompt-length=100 --decoder-prompt-length=100
```

**Comment by flymark2010** [comment]
@yh351016 The issue will be happened in vqa-gen task. It's OK in image_classify task, and no arguments added in evaluating config.

I've dig into the code and found that the issue is happened at the second generate step in `SequenceGenerator`（it's OK at the first step）.

**Comment by yh351016** [comment]
@flymark2010  
        if self.cross_self_attention or prev_output_tokens.eq(self.padding_idx).any():
            self_attn_padding_mask = prev_output_tokens.eq(self.padding_idx)
            if prompt_padding_mask is not None:
                self_attn_padding_mask = torch.cat([prompt_padding_mask, self_attn_padding_mask], dim=1)

**Comment by yh351016** [comment]
@flymark2010 try changing transformer.py:
if self.cross_self_attention or prev_output_tokens.eq(self.padding_idx).any():
    self_attn_padding_mask = prev_output_tokens.eq(self.padding_idx)
    if prompt_padding_mask is not None:
        self_attn_padding_mask = torch.cat([prompt_padding_mask, self_attn_padding_mask], dim=1)

---->
if self.cross_self_attention or prev_output_tokens.eq(self.padding_idx).any():
    self_attn_padding_mask = prev_output_tokens.eq(self.padding_idx)
if not incremental_state  and  prompt_padding_mask is not None:
    self_attn_padding_mask = torch.cat([prompt_padding_mask, self_attn_padding_mask], dim=1)

**Comment by yh351016** [comment]
@flymark2010 try changing transformer.py:
if self.cross_self_attention or prev_output_tokens.eq(self.padding_idx).any():
----self_attn_padding_mask = prev_output_tokens.eq(self.padding_idx)
----if prompt_padding_mask is not None:
--------self_attn_padding_mask = torch.cat([prompt_padding_mask, self_attn_padding_mask], dim=1)

---->
if self.cross_self_attention or prev_output_tokens.eq(self.padding_idx).any():
----self_attn_padding_mask = prev_output_tokens.eq(self.padding_idx)
if not incremental_state and prompt_padding_mask is not None:
----self_attn_padding_mask = torch.cat([prompt_padding_mask, self_attn_padding_mask], dim=1)

**Comment by flymark2010** [comment]
> @flymark2010 try changing transformer.py: if self.cross_self_attention or prev_output_tokens.eq(self.padding_idx).any(): ----self_attn_padding_mask = prev_output_tokens.eq(self.padding_idx) ----if prompt_padding_mask is not None: --------self_attn_padding_mask = torch.cat([prompt_padding_mask, self_attn_padding_mask], dim=1)
> 
> ----> if self.cross_self_attention or prev_output_tokens.eq(self.padding_idx).any(): ----self_attn_padding_mask = prev_output_tokens.eq(self.padding_idx) if not incremental_state and prompt_padding_mask is not None: ----self_attn_padding_mask = torch.cat([prompt_padding_mask, self_attn_padding_mask], dim=1)

Here got another error:
```
Traceback (most recent call last):
  File "../../evaluate.py", line 160, in <module>
    cli_main()
  File "../../evaluate.py", line 154, in cli_main
    distributed_utils.call_main(
  File "/workspace/project/OFA/fairseq/fairseq/distributed/utils.py", line 376, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/workspace/project/OFA/fairseq/fairseq/distributed/utils.py", line 350, in distributed_main
    main(cfg, **kwargs)
  File "../../evaluate.py", line 138, in main
    result, scores = eval_step(task, generator, models, sample, **kwargs)
  File "/workspace/project/OFA/utils/eval_utils.py", line 306, in eval_step
    return eval_vqa_gen(task, generator, models, sample, **kwargs)
  File "/workspace/project/OFA/utils/eval_utils.py", line 47, in eval_vqa_gen
    hypos = task.inference_step(generator, models, sample, prefix_tokens=sample['prefix_tokens'])
  File "/workspace/project/OFA/fairseq/fairseq/tasks/fairseq_task.py", line 517, in inference_step
    return generator.generate(
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/project/OFA/models/sequence_generator.py", line 209, in generate
    return self._generate(models, sample, **kwargs)
  File "/workspace/project/OFA/models/sequence_generator.py", line 354, in _generate
    lprobs, avg_attn_scores = model.forward_decoder(
  File "/workspace/project/OFA/models/sequence_generator.py", line 824, in forward_decoder
    decoder_out = model.decoder.forward(
  File "/workspace/project/OFA/models/ofa/unify_transformer.py", line 1343, in forward
    x, extra = self.extract_features(
  File "/workspace/project/OFA/models/ofa/unify_transformer.py", line 1367, in extract_features
    return self.extract_features_scriptable(
  File "/workspace/project/OFA/models/ofa/unify_transformer.py", line 1498, in extract_features_scriptable
    self_attn_padding_mask = torch.cat([prompt_padding_mask, self_attn_padding_mask], dim=1)
TypeError: expected Tensor as element 1 in argument 0, but got NoneType
```

**Comment by yh351016** [comment]
@flymark2010 
if self.cross_self_attention or prev_output_tokens.eq(self.padding_idx).any():
----self_attn_padding_mask = prev_output_tokens.eq(self.padding_idx)
----if prompt_padding_mask is not None:
--------self_attn_padding_mask = torch.cat([prompt_padding_mask, self_attn_padding_mask], dim=1)

---->
if self.cross_self_attention or prev_output_tokens.eq(self.padding_idx).any():
----self_attn_padding_mask = prev_output_tokens.eq(self.padding_idx)
----if not incremental_state and prompt_padding_mask is not None:
--------self_attn_padding_mask = torch.cat([prompt_padding_mask, self_attn_padding_mask], dim=1)

**Comment by flymark2010** [comment]
> @flymark2010 if self.cross_self_attention or prev_output_tokens.eq(self.padding_idx).any(): ----self_attn_padding_mask = prev_output_tokens.eq(self.padding_idx) ----if prompt_padding_mask is not None: --------self_attn_padding_mask = torch.cat([prompt_padding_mask, self_attn_padding_mask], dim=1)
> 
> ----> if self.cross_self_attention or prev_output_tokens.eq(self.padding_idx).any(): ----self_attn_padding_mask = prev_output_tokens.eq(self.padding_idx) ----if not incremental_state and prompt_padding_mask is not None: --------self_attn_padding_mask = torch.cat([prompt_padding_mask, self_attn_padding_mask], dim=1)

Same error like the first, but with different key_padding_mask size: 
```
Traceback (most recent call last):
  File "../../evaluate.py", line 160, in <module>
    cli_main()
  File "../../evaluate.py", line 154, in cli_main
    distributed_utils.call_main(
  File "/workspace/project/OFA/fairseq/fairseq/distributed/utils.py", line 376, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/workspace/project/OFA/fairseq/fairseq/distributed/utils.py", line 350, in distributed_main
    main(cfg, **kwargs)
  File "../../evaluate.py", line 138, in main
    result, scores = eval_step(task, generator, models, sample, **kwargs)
  File "/workspace/project/OFA/utils/eval_utils.py", line 306, in eval_step
    return eval_vqa_gen(task, generator, models, sample, **kwargs)
  File "/workspace/project/OFA/utils/eval_utils.py", line 47, in eval_vqa_gen
    hypos = task.inference_step(generator, models, sample, prefix_tokens=sample['prefix_tokens'])
  File "/workspace/project/OFA/fairseq/fairseq/tasks/fairseq_task.py", line 517, in inference_step
    return generator.generate(
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/project/OFA/models/sequence_generator.py", line 209, in generate
    return self._generate(models, sample, **kwargs)
  File "/workspace/project/OFA/models/sequence_generator.py", line 354, in _generate
    lprobs, avg_attn_scores = model.forward_decoder(
  File "/workspace/project/OFA/models/sequence_generator.py", line 824, in forward_decoder
    decoder_out = model.decoder.forward(
  File "/workspace/project/OFA/models/ofa/unify_transformer.py", line 1343, in forward
    x, extra = self.extract_features(
  File "/workspace/project/OFA/models/ofa/unify_transformer.py", line 1367, in extract_features
    return self.extract_features_scriptable(
  File "/workspace/project/OFA/models/ofa/unify_transformer.py", line 1535, in extract_features_scriptable
    x, layer_attn, _ = layer(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/project/OFA/models/ofa/unify_transformer_layer.py", line 500, in forward
    x, attn = self.self_attn(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/project/OFA/models/ofa/unify_multihead_attention.py", line 342, in forward
    assert key_padding_mask.size(1) == k.size(1), "{} vs {}".format(
AssertionError: 2 vs 102
```

**Comment by yh351016** [comment]
@flymark2010 I haven't reproduced relevant errors. When training vqa, do you have similar problems in validation dataset？

**Comment by flymark2010** [comment]
@yh351016 No error when val_inference_type=allcand, same error when val_inference_type=beamsearch

**Comment by yh351016** [comment]
@flymark2010 You can try to keep the length of the hey padding mask consistent with k.

**Comment by yh351016** [comment]
@flymark2010  if provided, specified padding elements in the key will be ignored by the attention. When given a binary mask and a value is True, the corresponding value on the attention layer will be ignored. When given a byte mask and a value is non-zero, the corresponding value on the attention layer will be ignored.
You can try to keep the length of the key padding mask consistent with k , filling with the same original value.

**Comment by flymark2010** [comment]
@yh351016 Thanks, I tried this and I can run evaluation now.
