### ISSUE TITLE
where is the json file which is test_predict.json when doing the inference and evaluation?

### ISSUE THREAD

**Issue by MrLianSYSU** [OFA-Sys/OFA#67]
When i am doing the inference and evaluation job ,after i run the command,it always raise the FileNOTfound error:can't find the test_predict.json in ../../results/caption/ ,so where is this test_predict.json file,can we have an satisifed answer?

**Comment by logicwong** [comment]
@MrLianSYSU Seems like you did not generate the test_predict.json in the inference stage, can you provide a more detailed error message?

**Comment by MrLianSYSU** [comment]
THE first error is ：
Traceback (most recent call last):
  File "/home/lianjunliang/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lianjunliang/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/lianjunliang/anaconda3/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/lianjunliang/anaconda3/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/lianjunliang/anaconda3/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/lianjunliang/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/lianjunliang/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/lianjunliang/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 


THE second raise error：
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
Loading and preparing results...
Traceback (most recent call last):
  File "/home/lianjunliang/anaconda3/envs/OFA/run_scripts/caption/coco_eval.py", line 38, in <module>
    evaluate_on_coco_caption(sys.argv[1], sys.argv[2])
  File "/home/lianjunliang/anaconda3/envs/OFA/run_scripts/caption/coco_eval.py", line 16, in evaluate_on_coco_caption
    cocoRes = coco.loadRes(res_file)
  File "/home/lianjunliang/anaconda3/lib/python3.9/site-packages/pycocotools/coco.py", line 319, in loadRes
    with open(resFile) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../results/caption/test_predict.json'

**Comment by MrLianSYSU** [comment]
@logicwong

**Comment by logicwong** [comment]
@MrLianSYSU Try inference with single gpu, like this:

```
#!/usr/bin/env bash

user_dir=../../ofa_module
bpe_dir=../../utils/BPE

data=../../dataset/caption_data/caption_test.tsv
path=../../checkpoints/caption_base_best.pt
result_path=../../results/caption
selected_cols=1,4,2
split='test'

CUDA_VISIBLE_DEVICES=0 python3 ../../evaluate.py \
    ${data} \
    --path=${path} \
    --user-dir=${user_dir} \
    --task=caption \
    --batch-size=16 \
    --log-format=simple --log-interval=10 \
    --seed=7 \
    --gen-subset=${split} \
    --results-path=${result_path} \
    --beam=5 \
    --max-len-b=16 \
    --no-repeat-ngram-size=3 \
    --fp16 \
    --num-workers=0 \
    --model-overrides="{\"data\":\"${data}\",\"bpe_dir\":\"${bpe_dir}\",\"eval_cider\":False,\"selected_cols\":\"${selected_cols}\"}"

python coco_eval.py ../../results/caption/test_predict.json ../../dataset/caption_data/test_caption_coco_format.json
```

**Comment by MrLianSYSU** [comment]
CUDA_VISIBLE_DEVICES=0 python3 -m torch.distributed.launch --nproc_per_node=${GPUS_PER_NODE} --master_port=${MASTER_PORT} ../../evaluate.py \
    ${data} \
    --path=${path} \
    --user-dir=${user_dir} \
    --task=caption \
    --batch-size=16 \
    --log-format=simple --log-interval=10 \
    --seed=7 \
    --gen-subset=${split} \
    --results-path=${result_path} \
    --beam=5 \
    --max-len-b=16 \
    --no-repeat-ngram-size=3 \
    --fp16 \
    --num-workers=0 \
    --model-overrides="{\"data\":\"${data}\",\"bpe_dir\":\"${bpe_dir}\",\"eval_cider\":False,\"selected_cols\":\"${selected_cols}\"}"

python coco_eval.py ../../results/caption/test_predict.json ../../dataset/caption_data/test_caption_coco_format.json

the result is the same:
loading annotations into memory...
Done (t=0.05s)
creating index...
index created!
Loading and preparing results...
Traceback (most recent call last):
  File "/home/lianjunliang/anaconda3/envs/OFA/run_scripts/caption/coco_eval.py", line 38, in <module>
    evaluate_on_coco_caption(sys.argv[1], sys.argv[2])
  File "/home/lianjunliang/anaconda3/envs/OFA/run_scripts/caption/coco_eval.py", line 16, in evaluate_on_coco_caption
    cocoRes = coco.loadRes(res_file)
  File "/home/lianjunliang/anaconda3/lib/python3.9/site-packages/pycocotools/coco.py", line 319, in loadRes
    with open(resFile) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../results/caption/test_predict.json'

Traceback (most recent call last):
  File "/home/lianjunliang/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lianjunliang/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/lianjunliang/anaconda3/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/lianjunliang/anaconda3/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/lianjunliang/anaconda3/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/lianjunliang/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/lianjunliang/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/lianjunliang/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by MrLianSYSU** [comment]
@logicwong

**Comment by logicwong** [comment]
![Uploading 50982AC1-E050-43EE-8B60-87CC5BD2B733.png…]()

**Comment by logicwong** [comment]
@MrLianSYSU 
<img width="912" alt="50982AC1-E050-43EE-8B60-87CC5BD2B733" src="https://user-images.githubusercontent.com/36780733/163677593-d7e8885e-2023-4eac-a306-2ae9d71a5896.png">

**Comment by MrLianSYSU** [comment]
it works thank you so much@logicwong
