### ISSUE TITLE
ConfigAttributeError when load the checkpoint

### ISSUE THREAD

**Issue by zd11024** [OFA-Sys/OFA#78]
Hi, Thanks for the great work! I meet problems when I load the pre-trained checkpoint (refcocog_large_best.pt). I load the model by
```
overrides={"bpe_dir":"utils/BPE"}
models, cfg, task = checkpoint_utils.load_model_ensemble_and_task(
        utils.split_paths('checkpoints/refcocog.pt'),
        arg_overrides=overrides
    )
```
The error occurs
```
Traceback (most recent call last):
  File "eval_refcoco.py", line 22, in <module>
    arg_overrides=overrides
  File "/home/tiger/.local/lib/python3.7/site-packages/fairseq-1.0.0a0+4095baa-py3.7-linux-x86_64.egg/fairseq/checkpoint_utils.py", line 457, in load_model_ensemble_and_task
    model = task.build_model(cfg.model)
  File "/opt/tiger/OFA_offical/tasks/mm_tasks/refcoco.py", line 79, in build_model
    if self.cfg.scst:
  File "/home/tiger/.local/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 305, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/tiger/.local/lib/python3.7/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/home/tiger/.local/lib/python3.7/site-packages/omegaconf/_utils.py", line 629, in format_and_raise
    _raise(ex, cause)
  File "/home/tiger/.local/lib/python3.7/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
  File "/home/tiger/.local/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 303, in __getattr__
    return self._get_impl(key=key, default_value=DEFAULT_VALUE_MARKER)
  File "/home/tiger/.local/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 361, in _get_impl
    node = self._get_node(key=key)
  File "/home/tiger/.local/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 383, in _get_node
    self._validate_get(key)
  File "/home/tiger/.local/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 136, in _validate_get
    key=key, value=value, cause=ConfigAttributeError(msg)
  File "/home/tiger/.local/lib/python3.7/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/home/tiger/.local/lib/python3.7/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/home/tiger/.local/lib/python3.7/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigAttributeError: Key 'scst' not in 'RefcocoConfig'
        full_key: scst
        reference_type=Optional[RefcocoConfig]
        object_type=RefcocoConfig
```
I would appreciate your help!

**Comment by logicwong** [comment]
@zd11024 Thanks for your feedback, We found a bug in refcoco.py, the latest code has fixed this bug. Please check out the latest code and have a try.

**Comment by Velcorn** [comment]
Getting the same error in a similar fashion when trying to load the ofa_tiny checkpoint during finetuning.
Log output: 
Key 'use_ema_weights_to_init_param' is not in struct 
full_key: checkpoint.use_ema_weights_to_init_param 
reference_type=Any 
object_type=dict

**Comment by jipson7** [comment]
Hi! Similar error when trying to load `caption_base_best.pt` for inference.

```
omegaconf.errors.ConfigKeyError: Key 'outputs' not in 'CaptionConfig'
	full_key: outputs
	reference_type=Optional[CaptionConfig]
	object_type=CaptionConfig

Process finished with exit code 1

```

**Comment by logicwong** [comment]
@zd11024 @Velcorn @jipson7 Seems like you used the official Fairseq repo? The official Fairseq repo doesn't handle the missing keys, Which may cause the error (See #63 for more details). We recommend you to use the Fairseq library provided in our repo.

Also, we will check all checkpoints and remove those useless keys.

**Comment by zd11024** [comment]
Many thanks! I have successfully run the inference code. Besides, I discovered that the lack of 'fairseq/examples/operators' in the provided Fairseq library could make the installation fail?

**Comment by logicwong** [comment]
@zd11024 Thanks for your feedback! Did you uninstall the original fairseq cleanly when you installed the provided Fairseq library?

**Comment by jipson7** [comment]
> @zd11024 @Velcorn @jipson7 Seems like you used the official Fairseq repo? The official Fairseq repo doesn't handle the missing keys, Which may cause the error (See #63 for more details). In addition, we also add some new configs in our fairseq library (e.g., `use_ema_weights_to_init_param`). **We recommend you to use the Fairseq library provided in our repo.**

Hi. No. I was using the fairseq from your repo, the larger checkpoint worked fine.

**Comment by logicwong** [comment]
@jipson7 Thanks for your feedback. We just updated `caption_base_best.pt`, please download `caption_base_best.pt` again and try it out. Hope the new checkpoint will solve your problem.

**Comment by jipson7** [comment]
@logicwong Thats awesome thank you. Ill try it right now.

**Comment by jipson7** [comment]
@logicwong That fixed it for me, thanks. Does the base model produce shorter sentences than the large?

**Comment by logicwong** [comment]
@jipson7 We have not compared the generation length of the base and large model. Maybe the large model has a stronger learning ability, so it can generate longer and more diverse sentences than the base model.
