### ISSUE TITLE
finetuning with Large model for image captioning (stage 2) with provided dataset 

### ISSUE THREAD

**Issue by Jihyun0510** [OFA-Sys/OFA#94]
Hello there
Thanks for your great work!

I encountered some errors while finetuning the large model in stage2, and need your help.

I downloaded the followings:
* Finetuned checkpoint for Caption on COCO During Stage1 Finetuing
* Dataset for Caption

After downloading the dataset and checkpoint, I ran the code you provided:
`nohup sh train_caption_stage2.sh > train_stage2.out &` 

```
Edited shell code is as followed:
export MASTER_PORT=1052

log_dir=./stage2_logs
save_dir=./stage2_checkpoints
mkdir -p $log_dir $ save_dir

bpe_dir=../../utils/BPE
user_dir=../../ofa_module

data_dir=../../dataset/caption_data
data=${data_dir}/caption_stage2_train_ori.tsv,${data_dir}/caption_val.tsv
restore_file=../../checkpoints/caption_stage1_best.pt
selected_cols=1,4,2

task=caption
arch=ofa_large
criterion=scst_reward_criterion
label_smoothing=0.1
lr=1e-5
max_epoch=5
warmup_ratio=0.06
batch_size=2
update_freq=4
resnet_drop_path_rate=0.0
encoder_drop_path_rate=0.0
decoder_drop_path_rate=0.0
dropout=0.0
attention_dropout=0.0
max_src_length=80
max_tgt_length=20
num_bins=1000
patch_image_size=480

eval_cider_cached=../../dataset/caption_data/cider_cached_tokens/coco-valid-words.p
scst_cider_cached=../../dataset/caption_data/cider_cached_tokens/coco-train-words.p

for lr in 1e-5; do
  echo "lr "${lr}
  for max_epoch in 3; do
    echo "max_epoch "${max_epoch}

    log_file=${log_dir}/${lr}"_"${max_epoch}".log"
    save_path=${save_dir}/${lr}"_"${max_epoch}
    mkdir -p $save_path

    # CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python3 -m torch.distributed.launch --nproc_per_node=8 --master_port=${MASTER_PORT} ../../train.py \
    echo "here"
    CUDA_VISIBLE_DEVICES=2,3 python3 -m torch.distributed.launch --nproc_per_node=2 --master_port=${MASTER_PORT} ../../train.py \
        $data \
        --selected-cols=${selected_cols} \
        --bpe-dir=${bpe_dir} \
        --user-dir=${user_dir} \
        --restore-file=${restore_file} \
        --reset-optimizer --reset-dataloader --reset-meters \
        --save-dir=${save_path} \
        --task=${task} \
        --arch=${arch} \
        --criterion=${criterion} \
        --batch-size=${batch_size} \
        --update-freq=${update_freq} \
        --encoder-normalize-before \
        --decoder-normalize-before \
        --share-decoder-input-output-embed \
        --share-all-embeddings \
        --layernorm-embedding \
        --patch-layernorm-embedding \
        --code-layernorm-embedding \
        --resnet-drop-path-rate=${resnet_drop_path_rate} \
        --encoder-drop-path-rate=${encoder_drop_path_rate} \
        --decoder-drop-path-rate=${decoder_drop_path_rate} \
        --dropout=${dropout} \
        --attention-dropout=${attention_dropout} \
        --weight-decay=0.01 --optimizer=adam --adam-betas="(0.9,0.999)" --adam-eps=1e-08 --clip-norm=1.0 \
        --lr-scheduler=polynomial_decay --lr=${lr} --end-learning-rate=2e-7 \
        --max-epoch=${max_epoch} --warmup-ratio=${warmup_ratio} \
        --log-format=simple --log-interval=10 \
        --fixed-validation-seed=7 \
        --no-epoch-checkpoints --keep-best-checkpoints=1 \
        --save-interval=1 --validate-interval=1 \
        --save-interval-updates=500 --validate-interval-updates=500 \
        --eval-cider \
        --eval-cider-cached-tokens=${eval_cider_cached} \
        --eval-args='{"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}' \
        --best-checkpoint-metric=cider --maximize-best-checkpoint-metric \
        --max-src-length=${max_src_length} \
        --max-tgt-length=${max_tgt_length} \
        --find-unused-parameters \
        --freeze-encoder-embedding \
        --freeze-decoder-embedding \
        --add-type-embedding \
        --scale-attn \
        --scale-fc \
        --scale-heads \
        --disable-entangle \
        --num-bins=${num_bins} \
        --patch-image-size=${patch_image_size} \
        --scst \
        --scst-cider-cached-tokens=${scst_cider_cached} \
        --scst-args='{"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}' \
        --memory-efficient-fp16 \
        --fp16-scale-window=512 \
        --num-workers=0 > ${log_file} 2>&1
  done
done
```

Running this shell file raised the following error:
```

2022-05-04 21:34:13 - trainer.py[line:798] - WARNING: attempting to recover from OOM in forward/backward pass
[]
/home/aaa/OFA/fairseq/fairseq/tasks/fairseq_task.py:559: UserWarning: ntokens not found in Criterion logging outputs, cannot log wpb or wps
  "ntokens not found in Criterion logging outputs, cannot log wpb or wps"
/home/aaa/OFA/fairseq/fairseq/tasks/fairseq_task.py:568: UserWarning: nsentences not found in Criterion logging outputs, cannot log bsz
  "nsentences not found in Criterion logging outputs, cannot log bsz"
Traceback (most recent call last):
  File "../../train.py", line 534, in <module>
    cli_main()
  File "../../train.py", line 525, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/aaa/OFA/fairseq/fairseq/distributed/utils.py", line 374, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/home/aaa/OFA/fairseq/fairseq/distributed/utils.py", line 348, in distributed_main
    main(cfg, **kwargs)
  File "../../train.py", line 194, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/home/aaa/miniconda3/envs/ofa2/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "../../train.py", line 305, in train
    log_output = trainer.train_step(samples)
  File "/home/aaa/miniconda3/envs/ofa2/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/aaa/OFA/trainer.py", line 1006, in train_step
    logging_outputs, sample_size, grad_norm
  File "/home/aaa/OFA/trainer.py", line 1451, in _reduce_and_log_stats
    self.task.reduce_metrics(logging_outputs, self.get_criterion())
  File "/home/aaa/OFA/tasks/mm_tasks/caption.py", line 163, in reduce_metrics
    super().reduce_metrics(logging_outputs, criterion)
  File "/home/aaa/OFA/fairseq/fairseq/tasks/fairseq_task.py", line 574, in reduce_metrics
    criterion.__class__.reduce_metrics(logging_outputs)
  File "/home/aaa/OFA/criterions/scst_loss.py", line 258, in reduce_metrics
    "loss", loss_sum / sample_size, sample_size, round=3
ZeroDivisionError: division by zero
[]
/home/aaa/OFA/fairseq/fairseq/tasks/fairseq_task.py:559: UserWarning: ntokens not found in Criterion logging outputs, cannot log wpb or wps
  "ntokens not found in Criterion logging outputs, cannot log wpb or wps"
/home/aaa/OFA/fairseq/fairseq/tasks/fairseq_task.py:568: UserWarning: nsentences not found in Criterion logging outputs, cannot log bsz
  "nsentences not found in Criterion logging outputs, cannot log bsz"
Traceback (most recent call last):
  File "../../train.py", line 534, in <module>
    cli_main()
  File "../../train.py", line 525, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/aaa/OFA/fairseq/fairseq/distributed/utils.py", line 374, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/home/aaa/OFA/fairseq/fairseq/distributed/utils.py", line 348, in distributed_main
    main(cfg, **kwargs)
  File "../../train.py", line 194, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/home/aaa/miniconda3/envs/ofa2/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "../../train.py", line 305, in train
    log_output = trainer.train_step(samples)
  File "/home/aaa/miniconda3/envs/ofa2/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/aaa/OFA/trainer.py", line 1006, in train_step
    logging_outputs, sample_size, grad_norm
  File "/home/aaa/OFA/trainer.py", line 1451, in _reduce_and_log_stats
    self.task.reduce_metrics(logging_outputs, self.get_criterion())
  File "/home/aaa/OFA/tasks/mm_tasks/caption.py", line 163, in reduce_metrics
    super().reduce_metrics(logging_outputs, criterion)
  File "/home/aaa/OFA/fairseq/fairseq/tasks/fairseq_task.py", line 574, in reduce_metrics
    criterion.__class__.reduce_metrics(logging_outputs)
  File "/home/aaa/OFA/criterions/scst_loss.py", line 258, in reduce_metrics
    "loss", loss_sum / sample_size, sample_size, round=3
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "/home/aaa/miniconda3/envs/ofa2/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/aaa/miniconda3/envs/ofa2/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/aaa/miniconda3/envs/ofa2/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/aaa/miniconda3/envs/ofa2/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/aaa/miniconda3/envs/ofa2/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/aaa/miniconda3/envs/ofa2/bin/python3', '-u', '../../train.py', '--local_rank=1', '../../dataset/caption_data/caption_stage2_train_ori.tsv,../../dataset/caption_data/caption_val.tsv', '--selected-cols=1,4,2', '--bpe-dir=../../utils/BPE', '--user-dir=../../ofa_module', '--restore-file=../../checkpoints/caption_stage1_best.pt', '--reset-optimizer', '--reset-dataloader', '--reset-meters', '--save-dir=./stage2_checkpoints/1e-5_3', '--task=caption', '--arch=ofa_large', '--criterion=scst_reward_criterion', '--batch-size=2', '--update-freq=4', '--encoder-normalize-before', '--decoder-normalize-before', '--share-decoder-input-output-embed', '--share-all-embeddings', '--layernorm-embedding', '--patch-layernorm-embedding', '--code-layernorm-embedding', '--resnet-drop-path-rate=0.0', '--encoder-drop-path-rate=0.0', '--decoder-drop-path-rate=0.0', '--dropout=0.0', '--attention-dropout=0.0', '--weight-decay=0.01', '--optimizer=adam', '--adam-betas=(0.9,0.999)', '--adam-eps=1e-08', '--clip-norm=1.0', '--lr-scheduler=polynomial_decay', '--lr=1e-5', '--end-learning-rate=2e-7', '--max-epoch=3', '--warmup-ratio=0.06', '--log-format=simple', '--log-interval=10', '--fixed-validation-seed=7', '--no-epoch-checkpoints', '--keep-best-checkpoints=1', '--save-interval=1', '--validate-interval=1', '--save-interval-updates=500', '--validate-interval-updates=500', '--eval-cider', '--eval-cider-cached-tokens=../../dataset/caption_data/cider_cached_tokens/coco-valid-words.p', '--eval-args={"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}', '--best-checkpoint-metric=cider', '--maximize-best-checkpoint-metric', '--max-src-length=80', '--max-tgt-length=20', '--find-unused-parameters', '--freeze-encoder-embedding', '--freeze-decoder-embedding', '--add-type-embedding', '--scale-attn', '--scale-fc', '--scale-heads', '--disable-entangle', '--num-bins=1000', '--patch-image-size=480', '--scst', '--scst-cider-cached-tokens=../../dataset/caption_data/cider_cached_tokens/coco-train-words.p', '--scst-args={"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}', '--memory-efficient-fp16', '--fp16-scale-window=512', '--num-workers=0']' returned non-zero exit status 1.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************

```

It seems like promblems are occuring when reading the dataset.
Becuase I think errors such as "UserWarning: ntokens not found in Criterion logging outputs, cannot log wpb or wps" arises due to empty data which then turns into 0 as default. 
Maybe this is the reason for the "ZeroDivisionError: division by zero" error?

**Comment by Jihyun0510** [comment]
I tried combinations of 3
resnet freeze + batch size=1 + update_freq=4
resnet freeze + batch size=2 + update_freq=8
resnet freeze + batch size=4 + update_freq=8
But still encountering the same error

The codes for the last combinationis as follwed:
```
export MASTER_PORT=1052

log_dir=./stage2_logs
save_dir=./stage2_checkpoints
mkdir -p $log_dir $ save_dir

bpe_dir=../../utils/BPE
user_dir=../../ofa_module

data_dir=../../dataset/caption_data
data=${data_dir}/caption_stage2_train_ori.tsv,${data_dir}/caption_val.tsv
restore_file=../../checkpoints/caption_stage1_best.pt
selected_cols=1,4,2

task=caption
arch=ofa_large
criterion=scst_reward_criterion
label_smoothing=0.1
lr=1e-5
max_epoch=5
warmup_ratio=0.06
batch_size=4
update_freq=8
resnet_drop_path_rate=0.0
encoder_drop_path_rate=0.0
decoder_drop_path_rate=0.0
dropout=0.0
attention_dropout=0.0
max_src_length=80
max_tgt_length=20
num_bins=1000
patch_image_size=480
# eval_cider_cached=${data_dir}/cider_cached_tokens/coco-valid-words.p
# scst_cider_cached=${data_dir}/cider_cached_tokens/coco-train-words.p

eval_cider_cached=../../dataset/caption_data/cider_cached_tokens/coco-valid-words.p
scst_cider_cached=../../dataset/caption_data/cider_cached_tokens/coco-train-words.p

for lr in 1e-5; do
  echo "lr "${lr}
  for max_epoch in 3; do
    echo "max_epoch "${max_epoch}

    log_file=${log_dir}/${lr}"_"${max_epoch}".log"
    save_path=${save_dir}/${lr}"_"${max_epoch}
    mkdir -p $save_path

    # CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python3 -m torch.distributed.launch --nproc_per_node=8 --master_port=${MASTER_PORT} ../../train.py \
    echo "here"
    CUDA_VISIBLE_DEVICES=2,3 python3 -m torch.distributed.launch --nproc_per_node=2 --master_port=${MASTER_PORT} ../../train.py \
        $data \
        --selected-cols=${selected_cols} \
        --bpe-dir=${bpe_dir} \
        --user-dir=${user_dir} \
        --restore-file=${restore_file} \
        --reset-optimizer --reset-dataloader --reset-meters \
        --save-dir=${save_path} \
        --task=${task} \
        --arch=${arch} \
        --criterion=${criterion} \
        --batch-size=${batch_size} \
        --update-freq=${update_freq} \
        --encoder-normalize-before \
        --decoder-normalize-before \
        --share-decoder-input-output-embed \
        --share-all-embeddings \
        --layernorm-embedding \
        --patch-layernorm-embedding \
        --code-layernorm-embedding \
        --resnet-drop-path-rate=${resnet_drop_path_rate} \
        --encoder-drop-path-rate=${encoder_drop_path_rate} \
        --decoder-drop-path-rate=${decoder_drop_path_rate} \
        --dropout=${dropout} \
        --attention-dropout=${attention_dropout} \
        --weight-decay=0.01 --optimizer=adam --adam-betas="(0.9,0.999)" --adam-eps=1e-08 --clip-norm=1.0 \
        --lr-scheduler=polynomial_decay --lr=${lr} --end-learning-rate=2e-7 \
        --max-epoch=${max_epoch} --warmup-ratio=${warmup_ratio} \
        --log-format=simple --log-interval=10 \
        --fixed-validation-seed=7 \
        --no-epoch-checkpoints --keep-best-checkpoints=1 \
        --save-interval=1 --validate-interval=1 \
        --save-interval-updates=500 --validate-interval-updates=500 \
        --eval-cider \
        --eval-cider-cached-tokens=${eval_cider_cached} \
        --eval-args='{"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}' \
        --best-checkpoint-metric=cider --maximize-best-checkpoint-metric \
        --max-src-length=${max_src_length} \
        --max-tgt-length=${max_tgt_length} \
        --find-unused-parameters \
        --freeze-encoder-embedding \
        --freeze-decoder-embedding \
        --freeze-resnet \
        --add-type-embedding \
        --scale-attn \
        --scale-fc \
        --scale-heads \
        --disable-entangle \
        --num-bins=${num_bins} \
        --patch-image-size=${patch_image_size} \
        --scst \
        --scst-cider-cached-tokens=${scst_cider_cached} \
        --scst-args='{"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}' \
        --memory-efficient-fp16 \
        --fp16-scale-window=512 \
        --num-workers=0 > ${log_file} 2>&1
  done
done
```

**Comment by Jihyun0510** [comment]
Moreover I am facing list index out of range and PIL.UnidentifiedImageError.
I used the same dateaset, only changed the image string part to mask it. 
So I do not understand why it raises list index out of range error. 
the way I created custom dataset is as follows:

```
def stringToRGB(base64_string):
    imgdata = base64.b64decode(base64_string)
    dataBytesIO = io.BytesIO(imgdata)
    image = Image.open(dataBytesIO)
    return image
    
path = '/home/aaa/OFA/dataset/caption_data/'

df = pd.read_csv("/home/aaa/OFA/dataset/caption_data/caption_stage2_train_ori.tsv", sep = '\t', header=None)

with open(path + 'caption_train.tsv', 'wt') as out_file:
    tsv_writer = csv.writer(out_file, delimiter='\t')
    for row in df.iterrows():
        # string to image
        r = list(row[1])       
        img = stringToRGB(r[-1])
        
        # image to array
        imgArray = np.array(img)
        width = imgArray.shape[1]
        mask_width = int(width*0.25)
        imgArray[:,:mask_width] = 1
        imgArray[:,width-mask_width:] = 1
         
        # array to image 
        img = Image.fromarray(imgArray)        

        # image to string
        img_buffer = BytesIO()
        img.save(img_buffer, format="JPEG")
        byte_data = img_buffer.getvalue()
        base64_str = base64.b64encode(byte_data) # bytes
        
        # write to tsv file
        tsv_writer.writerow([r[0], r[1], r[2], '', '', base64_str])

out_file.close()
```

The error code is as follows:
```

  File "/home/aaa/miniconda3/envs/ofa2/lib/python3.7/site-packages/PIL/Image.py", line 3124, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f0145749cb0>
local datafile ../../dataset/caption_data/caption_train.tsv slice_id 1 finished initializing row_count and line_idx-to-offset mapping
file ../../dataset/caption_data/caption_train.tsv slice_id 1 row count 56643 total row count 113287
Traceback (most recent call last):
  File "../../train.py", line 528, in <module>
    cli_main()
  File "../../train.py", line 521, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/aaa/OFA/fairseq/fairseq/distributed/utils.py", line 374, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/home/aaa/OFA/fairseq/fairseq/distributed/utils.py", line 348, in distributed_main
    main(cfg, **kwargs)
  File "../../train.py", line 161, in main
    disable_iterator_cache=True,
  File "/home/aaa/OFA/utils/checkpoint_utils.py", line 288, in load_checkpoint
    epoch=1, load_dataset=True, **passthrough_args
  File "/home/aaa/OFA/trainer.py", line 666, in get_train_iterator
    self.reset_dummy_batch(batch_iterator.first_batch)
  File "/home/aaa/OFA/fairseq/fairseq/data/iterators.py", line 322, in first_batch
    return self.collate_fn([self.dataset[i] for i in self.frozen_batches[0]])
  File "/home/aaa/OFA/fairseq/fairseq/data/iterators.py", line 322, in <listcomp>
    return self.collate_fn([self.dataset[i] for i in self.frozen_batches[0]])
  File "/home/aaa/OFA/data/mm_data/caption_dataset.py", line 117, in __getitem__
    uniq_id, image, caption = self.dataset[index]
  File "/home/aaa/OFA/data/file_dataset.py", line 106, in __getitem__
    column_l = [dtype(column_l[col_id]) for col_id, dtype in zip(self.selected_col_ids, self.dtypes)]
  File "/home/aaa/OFA/data/file_dataset.py", line 106, in <listcomp>
    column_l = [dtype(column_l[col_id]) for col_id, dtype in zip(self.selected_col_ids, self.dtypes)]
IndexError: list index out of range
```

Thank you so much for your help

**Comment by logicwong** [comment]
Please change `tsv_writer.writerow([r[0], r[1], r[2], '', '', base64_str])` to `tsv_writer.writerow([r[0], r[1], r[2], '', base64_str])`

**Comment by Jihyun0510** [comment]
Even after chaning the code, It keeps giving me "index out of range" error.
what i've found is, in file_dataset.py 
`column_l = [dtype(column_l[col_id]) for col_id, dtype in zip(self.selected_col_ids, self.dtypes)]`
some column_l has length of 1, so when col_id of 1,2,4 comes in, it raises out of range error.

I have checked my dataset which was made with the codes above, but there wasn't any row with a length less that 5.

that is why such error is a mystery.

**Comment by yangapku** [comment]
Hi, for the `UnidentifiedImageError`, please add a line `base64_str = base64_str.decode("utf-8")` after `base64_str = base64.b64encode(byte_data) # bytes`. As the code comment goes, the `base64_str` without decoding is bytes rather than string, which will be dumped with extra `b''` pattern in the output tsv file, causing error when reading.

**Comment by ahmadmobeen** [comment]
> Even after chaning the code, It keeps giving me "index out of range" error. what i've found is, in file_dataset.py `column_l = [dtype(column_l[col_id]) for col_id, dtype in zip(self.selected_col_ids, self.dtypes)]` some column_l has length of 1, so when col_id of 1,2,4 comes in, it raises out of range error.
> 
> I have checked my dataset which was made with the codes above, but there wasn't any row with a length less that 5.
> 
> that is why such error is a mystery.

Hi, Could you please explain, how did you solve this error? I am facing the same error. In my understanding, it has something to do with the offset calculation.
