### ISSUE TITLE
Script to obtain the image code (using VQ-GAN)

### ISSUE THREAD

**Issue by allanj** [OFA-Sys/OFA#99]
I'm trying to pre-training on my custom dataset. But it seems I cannot directly find the script to generate the image code using VQ-GAN.

Is it possible to provide this script for us? Or any link that I can refer to

**Comment by jxst539246** [comment]
hi, please check [run_scripts/image_gen/generate_for_vqgan_code.sh](https://github.com/OFA-Sys/OFA/blob/main/run_scripts/image_gen/generate_for_vqgan_code.sh) .

**Comment by allanj** [comment]
Thanks.

**Comment by taokz** [comment]
Hi! Thanks for your amazing work!

I have an issue when I run 'generate_for_vqgan_code.sh' using my customized dataset. I follow the guidance to create an (image-only) input files (.txt) like:

12345 \t /9j/4AAQSkZJ....UCP/2Q== \n
12346 \t /9j/4AAQSkZJ....UCP/2Q== \n
where \t means tabs, \n means newlines. I use images with 390x320 size.

However, when I run the script, I got RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`. The details are shown as follows:

Traceback (most recent call last):
  File "generate_code.py", line 121, in <module>
    z, _, [_, _, image_codes] = image_tokenizer.encode(data["code_image"].cuda())
  File "../../models/taming/models/vqgan.py", line 55, in encode
    h = self.encoder(x)
  File "/home/test/anaconda3/envs/test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "../../models/taming/modules/diffusionmodules/model.py", line 418, in forward
    h = self.down[i_level].attn[i_block](h)
  File "/home/test/anaconda3/envs/test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "../../models/taming/modules/diffusionmodules/model.py", line 180, in forward
    w_ = torch.bmm(q,k)     # b,hw,hw    w[b,i,j]=sum_c q[b,i,c]k[b,c,j]
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

Could you provide some hints and suggestions to help solve this issue. I appreciate your help, thanks!
